# Extract KEGG info

In [1]:
import sys
sys.path.append('../../../')

from file_management import get_files_dir,check_save_file
_, INPUT_DIR, OUTPUT_DIR = get_files_dir()

In [2]:
import requests
import sys
from io import StringIO
import re
import pandas as pd

def generate_url(taxid):
    #start_url = 'https://rest.uniprot.org/uniprotkb/stream?fields=accession%2Creviewed%2Cid%2Cprotein_name%2Cgene_names%2Corganism_name%2Cgene_synonym&format=tsv&query=%28%28taxonomy_id%3A'
#    start_url = 'https://rest.uniprot.org/uniprotkb/stream?fields=accession%2Cid%2Cgene_names%2Corganism_name%2Cec%2Crhea%2Cxref_kegg%2Cxref_geneid%2Cxref_ko%2Cxref_brenda%2Cxref_unipathway%2Cgo_id%2Cgene_synonym&format=tsv&query=%28%28taxonomy_id%3A'
    start_url = 'https://rest.uniprot.org/uniprotkb/stream?fields=accession%2Cid%2Cgene_names%2Corganism_name%2Cec%2Crhea%2Cxref_kegg%2Cxref_geneid%2Cxref_kegg%2Cxref_brenda%2Cxref_unipathway%2Cgo_id%2Cgene_synonym&format=tsv&query=%28%28taxonomy_id%3A'
    end_url = '%29%29%20AND%20%28reviewed%3Atrue%29'
    url = start_url+taxid+end_url
    return(url)

def retrieve_data(url):
    all_fastas = requests.get(url)
    TESTDATA = StringIO(all_fastas.text)
    genes_pd = pd.read_table(TESTDATA)
    return(genes_pd)

In [3]:
def get_kegg_KO():
    url  = "https://www.genome.jp/kegg-bin/download_htext?htext=eco00001&format=htext&filedir=kegg/brite/eco"

In [4]:
file = OUTPUT_DIR+'/Articles/full_text_w_genes_24_08_29.json'
org_prod = pd.read_json(file)

org_prod

In [5]:
org_prod.Genes.dropna()

0           [[speD, A0A4V7TT54, 0], [speE, A0A1Y0XKU0, 0]]
3        [[and, P73507_P74389, syn:slr0446;syn:sll1360;...
4        [[JW1087, A0A066RFP3_A0A0H2YXQ2_A0A0H3MHP8_A0A...
5        [[glgP, P73511_P73546, syn:slr1367;syn:sll1356...
7        [[papR1, D9UBV4, spri:SPRI_0302;spri:SPRI_7051...
                               ...
10695                 [[CYP102A1, P14779, bmeg:BG04_163;]]
10696    [[ADH1, Q07288, 0], [ADH2, Q9P4C2, 0], [ADH3, ...
10697    [[cre, A0A0E1M686, 0], [neo, P00551_Q79DX9, ag...
10698                              [[laeA, A0A1V0FZV9, 0]]
10699    [[DnaJ, M1EZQ5, 0], [dcm, A0A066SWY3_A0A0F3TQQ...
Name: Genes, Length: 5520, dtype: object

filter fake friends >:C

In [6]:
#check = org_prod.Genes.str[0].str[0]!='Try_again'
remove_empty = org_prod.dropna(subset=['Genes'])
remove_empty.head()

,Title,PM_ID,Abstract,Journal,Year,PMC_ID,DOI,Type,Author,Classification,Text,Abstract_min,Title_min,Full_text_min,Old_name,Organism,Genes
0,Biosynthesis of a Novel Bioactive Metabolite o...,33356220,Spermidine is a biologically active polyamine ...,Journal of agricultural and food chemistry,2021,NaN,10.1021/acs.jafc.0c07143,"Journal Article,","[ForeName:Dian,LastName:Zou] [ForeName:Lu,Last...",1,None,Spermidine polyamine application foods. Howeve...,Biosynthesis Novel Bioactive Metabolite Spermi...,,[Bacillus amyloliquefaciens],[Bacillus amyloliquefaciens],"[[speD, A0A4V7TT54, 0], [speE, A0A1Y0XKU0, 0]]"
3,Metabolic Engineering and Comparative Performa...,26732758,Wood sugars such as xylose can be used as an i...,Frontiers in microbiology,2015,4689873.0,10.3389/fmicb.2015.01484,"Journal Article,","[ForeName:Saurabh,LastName:Ranade] [ForeName:Y...",1,\n Introduction \n Lignocellulosic...,Wood sugars xylose carbon source biotechnologi...,Metabolic Engineering Comparative Performance ...,"Introduction Lignocellulosic abundant, inexpen...",[Synechocystis PCC],[Synechocystis PCC],"[[and, P73507_P74389, syn:slr0446;syn:sll1360;..."
4,Improving D-glucaric acid production from myo-...,24333274,D-glucaric acid has been explored for a myriad...,Metabolic engineering,2014,NaN,10.1016/j.ymben.2013.12.002,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:Eric,LastName:Shiue] [ForeName:Krist...",1,Metabolic Engineering 22 (2014) 22–31\n\nConte...,"D-glucaric explored uses, including biopolymer...",Improving D-glucaric production myo-inositol E...,Metabolic Engineering (2014) 22–31 Contents li...,[E coli],[Escherichia coli],"[[JW1087, A0A066RFP3_A0A0H2YXQ2_A0A0H3MHP8_A0A..."
5,Increased bioplastic production with an RNA po...,23861321,Because cyanobacteria directly harvest CO2 and...,DNA research : an international journal for ra...,2013,3859321.0,10.1093/dnares/dst028,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:Takashi,LastName:Osanai] [ForeName:K...",1,\n 1. \n Introduction \n Cya...,"cyanobacteria harvest CO2 energy, carbon metab...",Increased bioplastic production RNA polymerase...,1. Introduction Cyanobacteria utilize energy v...,[Synechocystis PCC],[Synechocystis PCC],"[[glgP, P73511_P73546, syn:slr1367;syn:sll1356..."
7,A stepwise increase in pristinamycin II biosyn...,25708513,"Pristinamycin, which is a streptogramin antibi...",Metabolic engineering,2015,NaN,10.1016/j.ymben.2015.02.001,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:Lei,LastName:Li] [ForeName:Yawei,Las...",1,None,"Pristinamycin, streptogramin produced Streptom...",increase pristinamycin II biosynthesis Strepto...,,[Streptomyces pristinaespiralis],[Streptomyces pristinaespiralis],"[[papR1, D9UBV4, spri:SPRI_0302;spri:SPRI_7051..."

In [7]:
def flatten_level_3_list(level_3_list):
    if len(level_3_list[0][0][0])!=1:
        level_2_list = [inner for outer in level_3_list for inner in outer]
        return level_2_list
    else :
        return level_3_list

fake_friend_word = ['well','many','operon','smal','like','product','case',
                    'this', 'putative','core','aci','top','heme','last',
                    'nine','reverse','beta','iron','eco','subunit','past',
                    'map','cat','partial','para','enzyme','high','small',
                   'pure','year','synthase','plasmid','alpha','dead','gap','con','com',
                   'pro']

In [8]:
fake_friend_word = ['mauauuu']

In [9]:
remove_empty.Genes

0           [[speD, A0A4V7TT54, 0], [speE, A0A1Y0XKU0, 0]]
3        [[and, P73507_P74389, syn:slr0446;syn:sll1360;...
4        [[JW1087, A0A066RFP3_A0A0H2YXQ2_A0A0H3MHP8_A0A...
5        [[glgP, P73511_P73546, syn:slr1367;syn:sll1356...
7        [[papR1, D9UBV4, spri:SPRI_0302;spri:SPRI_7051...
                               ...
10695                 [[CYP102A1, P14779, bmeg:BG04_163;]]
10696    [[ADH1, Q07288, 0], [ADH2, Q9P4C2, 0], [ADH3, ...
10697    [[cre, A0A0E1M686, 0], [neo, P00551_Q79DX9, ag...
10698                              [[laeA, A0A1V0FZV9, 0]]
10699    [[DnaJ, M1EZQ5, 0], [dcm, A0A066SWY3_A0A0F3TQQ...
Name: Genes, Length: 5520, dtype: object

In [10]:
remove_empty.Genes = remove_empty.Genes.apply(flatten_level_3_list)

/var/folders/v6/y2v6wwn93yj5vvhl558fx2zc0000gn/T/ipykernel_65240/1453033910.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  remove_empty.Genes = remove_empty.Genes.apply(flatten_level_3_list)

In [11]:
remove_empty.shape

(5520, 17)

In [12]:
fake_friends = remove_empty.Genes.explode().reset_index()

In [13]:
fake_friends

       index                                              Genes
0          0                              [speD, A0A4V7TT54, 0]
1          0                              [speE, A0A1Y0XKU0, 0]
2          3     [and, P73507_P74389, syn:slr0446;syn:sll1360;]
3          3                       [glgC, P52415, syn:slr1176;]
4          3                       [petA, P26287, syn:sll1317;]
...      ...                                                ...
45908  10698                              [laeA, A0A1V0FZV9, 0]
45909  10699                                  [DnaJ, M1EZQ5, 0]
45910  10699  [dcm, A0A066SWY3_A0A0F3TQQ5_A0A0H2V8A4_A0A0H2Y...
45911  10699  [lacI, A0A080JDE0_A0A0E0Y329_A0A0H2YWK6_A0A0H3...
45912  10699  [marA, A0A080J1J4_A0A0H2V7G9_A0A0H2YZM0_A0A0H3...

[45913 rows x 2 columns]

In [14]:
#fake_friends = remove_empty.Genes.dropna().explode()
KEGG_filter  = fake_friends.loc[~fake_friends.Genes.str[0].isin(fake_friend_word)]
KEGG_filter

       index                                              Genes
0          0                              [speD, A0A4V7TT54, 0]
1          0                              [speE, A0A1Y0XKU0, 0]
2          3     [and, P73507_P74389, syn:slr0446;syn:sll1360;]
3          3                       [glgC, P52415, syn:slr1176;]
4          3                       [petA, P26287, syn:sll1317;]
...      ...                                                ...
45908  10698                              [laeA, A0A1V0FZV9, 0]
45909  10699                                  [DnaJ, M1EZQ5, 0]
45910  10699  [dcm, A0A066SWY3_A0A0F3TQQ5_A0A0H2V8A4_A0A0H2Y...
45911  10699  [lacI, A0A080JDE0_A0A0E0Y329_A0A0H2YWK6_A0A0H3...
45912  10699  [marA, A0A080J1J4_A0A0H2V7G9_A0A0H2YZM0_A0A0H3...

[45913 rows x 2 columns]

In [20]:
KEGG_id_list = KEGG_filter.copy()

In [21]:
KEGG_id_list.loc[:,'KEGG_search'] = KEGG_filter.Genes.str[2].str.rstrip(';').str.split(';')

In [22]:
KEGG_id_list.head()

,index,Genes,KEGG_search
0,0,"[speD, A0A4V7TT54, 0]",NaN
1,0,"[speE, A0A1Y0XKU0, 0]",NaN
2,3,"[and, P73507_P74389, syn:slr0446;syn:sll1360;]","[syn:slr0446, syn:sll1360]"
3,3,"[glgC, P52415, syn:slr1176;]",[syn:slr1176]
4,3,"[petA, P26287, syn:sll1317;]",[syn:sll1317]

In [23]:
org_KEDD_ID = KEGG_id_list.KEGG_search.explode().str.split(':').str[0].drop_duplicates().dropna()

In [24]:
org_KEDD_ID.drop_duplicates().dropna()

2        syn
13       ecg
13       ecq
13       eum
13       ecx
        ...
45574    pub
45580    aae
45596    apo
45628    ssa
45636    mja
Name: KEGG_search, Length: 738, dtype: object

In [27]:
organism_dataframes = []
for organism_id in org_KEDD_ID:
    organism_id = str(organism_id)
    try:
        # Open the file
        kegg_info = pd.read_csv(f'../../KEGG_genes/{organism_id}.csv')
        kegg_info = kegg_info.set_index('KO')
        organism_dataframes.append(kegg_info)
        #print(kegg_info.head())
    except:
        # Get the file
        #print('getting_new')
        url  = f"https://www.genome.jp/kegg-bin/download_htext?htext={organism_id}00001&format=htext&filedir=kegg/brite/{organism_id}"
        raw_info = requests.get(url)
        text_info = StringIO(raw_info.text)

        # extract important information
        gene_info = []
        for line in text_info.readlines():
            if line.startswith('D'):
                filtered_line = line.rstrip()[7:]
                gene_info.append(filtered_line.split('\t'))

        kegg_info = pd.DataFrame(gene_info,columns=[f'Gene_{organism_id}','KO'])

        kegg_info.loc[:,f'Gene_{organism_id}'] = organism_id+':'+kegg_info.loc[:,f'Gene_{organism_id}'].str.split(' ').str[0]+';'
        kegg_info.KO = kegg_info.KO.str.split(' ').str[0]
        kegg_info.set_index('KO',inplace=True)
        kegg_info.drop_duplicates(inplace=True)
        kegg_info = kegg_info.groupby(level=0).sum()
        organism_dataframes.append(kegg_info)
        kegg_info.to_csv(f'../../KEGG_genes/{organism_id}.csv')

In [28]:
full_info = pd.concat(organism_dataframes,axis=1)

Get the KO for each genen in each organism ?

In [29]:
full_info.head()

,Gene_syn,Gene_ecg,Gene_ecq,Gene_eum,Gene_ecx,Gene_ece,Gene_ecs,Gene_elo,Gene_eck,Gene_elw,...,Gene_kvq,Gene_ron,Gene_kpu,Gene_pfl,Gene_pprc,Gene_pub,Gene_aae,Gene_apo,Gene_ssa,Gene_mja
KO,,,,,,,,,,,,,,,,,,,,,
K00002,syn:slr0942;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
K00003,syn:sll0455;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,pfl:PFL_3809;pfl:PFL_1103;,pprc:PFLCHA0_c11230;pprc:PFLCHA0_c38630;,pub:SAR11_1025;,aae:aq_1812;,apo:Arcpr_0276;,ssa:SSA_1043;,mja:MJ_1602;
K00012,syn:slr1299;,ecg:E2348C_2169;,ecq:ECED1_2377;,eum:ECUMN_2370;,ecx:EcHS_A2178;,ece:Z3190;,ecs:ECs_2829;,elo:EC042_2271;,eck:EC55989_2287;,elw:ECW_m2188;,...,kvq:SP68_06460;,ron:TE10_19240;,kpu:KP1_3701;,pfl:PFL_3078;pfl:PFL_3050;,pprc:PFLCHA0_c31090;pprc:PFLCHA0_c30780;,pub:SAR11_1086;,aae:aq_024;,apo:Arcpr_1218;,NaN,mja:MJ_1054;
K00013,syn:slr0682;syn:slr1848;,ecg:E2348C_2161;,ecq:ECED1_2369;,eum:ECUMN_2362;,ecx:EcHS_A2159;,ece:Z3182;,ecs:ECs_2821;,elo:EC042_2263;,eck:EC55989_2279;,elw:ECW_m2180;,...,kvq:SP68_06380;,ron:TE10_19140;,kpu:KP1_3680;,pfl:PFL_0929;,pprc:PFLCHA0_c09440;,pub:SAR11_0475;,aae:aq_782;,apo:Arcpr_0997;,ssa:SSA_1446;,mja:MJ_1456;
K00020,syn:slr0229;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,kvq:SP68_01955;,NaN,kpu:KP1_2739;,pfl:PFL_2928;pfl:PFL_1303;pfl:PFL_0748;,pprc:PFLCHA0_c07580;pprc:PFLCHA0_c29730;pprc:P...,pub:SAR11_0863;pub:SAR11_1196;,aae:aq_038;,NaN,NaN,NaN

In [ ]:
general_name = 'full_kegg'

today = date.today()
today = today.strftime("%y_%m_%d")

output_file = f'{general_name}_V_{today}.json'
output_file

In [31]:
full_info.to_csv('full_kegg_june_20.csv')

full_info = pd.read_csv('full_kegg.csv',dtype=str)

full_info = full_info.set_index('KO')

In [32]:
full_info.columns

Index(['Gene_syn', 'Gene_ecg', 'Gene_ecq', 'Gene_eum', 'Gene_ecx', 'Gene_ece',
       'Gene_ecs', 'Gene_elo', 'Gene_eck', 'Gene_elw',
       ...
       'Gene_kvq', 'Gene_ron', 'Gene_kpu', 'Gene_pfl', 'Gene_pprc', 'Gene_pub',
       'Gene_aae', 'Gene_apo', 'Gene_ssa', 'Gene_mja'],
      dtype='object', length=736)

# Maua

In [33]:
def buscar_magia(lista):
    for gene_kegg in lista:
        org = gene_kegg.split(':')[0]
        #gene = gene.split(':')[1]
        if f'Gene_{org}' in full_info:
            kegg_db = full_info.loc[:,f'Gene_{org}'].dropna().str.rstrip(';')
            kegg_db = kegg_db.str.split(';').explode()
            new_gene = kegg_db.index[kegg_db==gene_kegg]
            if not new_gene.empty:
                return(new_gene[0])

In [34]:
KEGG_id_list[KEGG_id_list.Genes.str[0]=='ADH']

       index                                      Genes       KEGG_search
2620     617                       [ADH, A0A098BGW7, 0]               NaN
7140    1731                           [ADH, E0NHX4, 0]               NaN
11604   2696                           [ADH, P25984, 0]               NaN
13959   3334                       [ADH, A0A0H3WN09, 0]               NaN
14238   3401                       [ADH, A0A0H3WN09, 0]               NaN
14251   3401                           [ADH, H9L7T3, 0]               NaN
17609   4137                           [ADH, D0V8B9, 0]               NaN
25760   6094                [ADH, Q8DWE2, smu:SMU_119;]     [smu:SMU_119]
28540   6637                           [ADH, D0V8B9, 0]               NaN
29579   6803                       [ADH, A0A0H3WN09, 0]               NaN
31346   7216                           [ADH, H9L7T3, 0]               NaN
31851   7302                       [ADH, A0A0H3WN09, 0]               NaN
32192   7410                       [ADH, A0A0H3WN09, 0]               NaN
33703   7755                           [ADH, H9L7T3, 0]               NaN
37114   8553                       [ADH, A0A0H3WN09, 0]               NaN
37266   8595                           [ADH, P14941, 0]               NaN
37267   8595                       [ADH, A0A3P4ASJ4, 0]               NaN
42496   9861  [ADH, A0A132HTY5_C5C7C3, mlu:Mlut_21430;]  [mlu:Mlut_21430]

In [35]:
KEGG_id_list.head(60)

,index,Genes,KEGG_search
0,0,"[speD, A0A4V7TT54, 0]",NaN
1,0,"[speE, A0A1Y0XKU0, 0]",NaN
2,3,"[and, P73507_P74389, syn:slr0446;syn:sll1360;]","[syn:slr0446, syn:sll1360]"
3,3,"[glgC, P52415, syn:slr1176;]",[syn:slr1176]
4,3,"[petA, P26287, syn:sll1317;]",[syn:sll1317]
5,3,"[psbA2, P16033_Q83TK2, syn:sll1867;syn:slr1311;]","[syn:sll1867, syn:slr1311]"
6,3,"[sll0771, P15729, syn:sll0771;]",[syn:sll0771]
7,3,"[sll1317, P26287, syn:sll1317;]",[syn:sll1317]
8,3,"[slr0168, Q55549, syn:slr0168;]",[syn:slr0168]
9,3,"[slr1176, P52415, syn:slr1176;]",[syn:slr1176]
10,3,"[slr1285, P74199, syn:slr1285;]",[syn:slr1285]
11,3,"[talB, P72797, syn:slr1793;]",[syn:slr1793]
12,3,"[tktA, P73282, syn:sll1070;]",[syn:sll1070]
13,4,"[JW1087, A0A066RFP3_A0A0H2YXQ2_A0A0H3MHP8_A0A7...","[ecg:E2348C_3254, ecq:ECED1_5002, eum:ECUMN_29..."
14,4,"[TetR, B1VCF0, 0]",NaN
15,4,"[araB, A0A0E0Y5I0_A0A0E0Y7K1_A0A0H3ECT0_A0A0H3...","[ecr:ECIAI1_0063, ect:ECIAI39_0066, ecf:ECH741..."
16,4,"[araC, A0A061KXT6_A0A0E0Y3Y4_A0A0H2V408_A0A0H2...","[ebd:ECBD_3556, ecw:EcE24377A_0063, elw:ECW_m0..."
17,4,"[araD, A0A061KXT6_A0A0E0Y3Y4_A0A0H2V408_A0A0H2...","[ebd:ECBD_3556, ecw:EcE24377A_0063, elw:ECW_m0..."
18,4,"[endA, A0A080ILD5_A0A0H2VCU8_A0A0H2Z2G5_A0A0H3...","[ecs:ECs_3821, ecw:EcE24377A_3288, ecz:ECS88_3..."
19,4,"[galK, A0A023LD42_A0A0E0Y2C6_A0A0H3EGM2_A1A900...","[ecf:ECH74115_0860, ecg:E2348C_0634, ecw:EcE24..."
20,4,"[galU, A0A080J3J0_A0A0H2YYE4_A0A0H3MGG5_A0A7I6...","[ece:Z2012, ecs:ECs_1738, elw:ECW_m1328, elo:E..."
21,4,"[gudD, A0A061KWG2_A0A0H2VAA3_A0A0H2Z236_A0A0H3...","[eum:ECUMN_3116, ect:ECIAI39_3209, eci:UTI89_C..."
22,4,"[ilvG, A0A0H2VCU0_A0A0H2Z5D3_A0A0H3MJV6_A0A6M7...","[ecm:EcSMS35_4134, ecv:APECO1_2703, eci:UTI89_..."
23,4,"[kan, Q9JMV2, 0]",NaN
24,4,"[lacI, A0A080JDE0_A0A0E0Y329_A0A0H2YWK6_A0A0H3...","[ecw:EcE24377A_0369, ecj:JW0336, eco:b0345, es..."
25,4,"[manX, A0A0F3VW50_A0A0H2YZT1_A0A0H3MFS3_A0A7I6...","[ecv:APECO1_874, ece:Z2860, ecs:ECs_2527, ecg:..."
26,4,"[mcrA, A0A2X1MVW2_P24200, ecj:JW1145;eco:b1159;]","[ecj:JW1145, eco:b1159]"
27,4,"[mrr, A0A024L7D6_A0A0H2Z6U6_B7NH06_P24202_Q1R2...","[ecv:APECO1_2075, eum:ECUMN_4960, eci:UTI89_C5..."
28,4,"[nupG, A0A066SVP2_A0A0E0XW24_A0A0H2VAM7_A0A0H2...","[eln:NRG857_14565, eck:EC55989_3257, ecj:JW293..."
29,4,"[ptsG, A0A066RFP3_A0A0H2YXQ2_A0A0H3MHP8_A0A7I6...","[ecg:E2348C_3254, ecq:ECED1_5002, eum:ECUMN_29..."
30,4,"[recA, A0A0E0XX21_A0A0E1M0L9_A0A0H2Z1Z1_A0A0H3...","[ecz:ECS88_2962, esl:O3K_06080, ecv:APECO1_382..."
31,4,"[rhaB, A0A066T5B3_A0A0E0Y5L9_A0A0H3EPJ6_A0A140...","[ebd:ECBD_4120, esl:O3K_24345, ect:ECIAI39_309..."
32,4,"[rhaD, A0A024L7K5_A0A0E0Y5V3_A0A0H3ENN9_A0A140...","[ecc:c4851, ecr:ECIAI1_4107, ect:ECIAI39_3095,..."
33,4,"[ric, A0A080I8P6, 0]",NaN
34,4,"[rph, A0A0E0XSS6_A0A0H3ENI9_A0A0H3MRK0_A0A140N...","[ecl:EcolC_0068, elw:ECW_m3919, ebw:BWG_3334, ..."
35,4,"[rpsL, A0A075MCD8_A0A0E0XWU7_A0A0H3EMK4_A0A140...","[ecl:EcolC_0371, ecw:EcE24377A_3811, ecf:ECH74..."
36,4,"[tetR, A0A0H2XJP6_A0A0H3ER07_B1LRX5_B7LJ03_D3H...","[elo:EC042_4110, eln:NRG857_30068, ecm:EcSMS35..."
37,4,"[uxaC, A0A080IQQ2_A0A0E0XTU6_A0A0H3EPS0_A0A140...","[ece:Z4445, ecs:ECs_3974, eln:NRG857_15390, eu..."
38,4,"[yoaE, A0A0C2B5U4_A0A0H2YZF6_A0A0H3MFI5_B7L6U4...","[ecv:APECO1_873, elw:ECW_m1986, eck:EC55989_19..."
39,5,"[glgP, P73511_P73546, syn:slr1367;syn:sll1356;]","[syn:slr1367, syn:sll1356]"
40,5,"[glgX, P72691_P73608, syn:slr0237;syn:slr1857;]","[syn:slr0237, syn:slr1857]"
41,5,"[glnB, Q55247, syn:ssl0707;]",[syn:ssl0707]
42,5,"[gnd, P52208, syn:sll0329;]",[syn:sll0329]
43,5,"[opcA, P73720, syn:slr1734;]",[syn:slr1734]
44,5,"[phaA, P73825, syn:slr1993;]",[syn:slr1993]
45,5,"[phaB, P73826, syn:slr1994;]",[syn:slr1994]
46,5,"[phaC, P73390, syn:slr1830;]",[syn:slr1830]
47,5,"[phaE, P73389, syn:slr1829;]",[syn:slr1829]
48,5,"[sll0461, Q55167, syn:sll0461;]",[syn:sll0461]
49,5,"[sll0565, P74742, syn:sll0565;]",[syn:sll0565]
50,5,"[sll1356, P73511_P73546, syn:slr1367;syn:sll13...","[syn:slr1367, syn:sll1356]"
51,5,"[tal, P72797, syn:slr1793;]",[syn:slr1793]
52,5,"[zwf, P73411, syn:slr1843;]",[syn:slr1843]
53,7,"[papR1, D9UBV4, spri:SPRI_0302;spri:SPRI_7051;]","[spri:SPRI_0302, spri:SPRI_7051]"
54,7,"[papR3, D9UBW8, 0]",NaN
55,7,"[papR4, D9UBW9, spri:SPRI_0318;spri:SPRI_7035;]","[spri:SPRI_0318, spri:SPRI_7035]"
56,7,"[papR5, D9UBX0, 0]",NaN
57,7,"[papR6, D9UBK2, spri:SPRI_0195;spri:SPRI_7158;]","[spri:SPRI_0195, spri:SPRI_7158]"
58,7,"[spbR, Q8VVP1, spri:SPRI_0321;spri:SPRI_7032;]","[spri:SPRI_0321, spri:SPRI_7032]"
59,9,"[ABZ1, A0A8H4F807_P37254, sce:YNR033W;]",[sce:YNR033W]

In [36]:
KEGG_id_list[KEGG_id_list.KEGG_search.isna()].Genes.str[0].value_counts().head(60)

Genes
kan      132
URA3      98
ldhA      76
ldh       71
adhE      62
met       62
ter       60
pyc       54
sacB      52
bis       51
LDH       50
alsS      46
GAP       45
pta       42
tem       41
rfb       40
sfp       40
tet       37
ent       35
XPR2      35
gapA      34
tkt       32
phaC      32
GAPDH     32
hpt       30
ArcA      30
TetR      30
hbd       30
GSH       29
adh       29
gdh       29
PEX10     27
pir       26
fdh       26
Int       26
ACT       25
budA      25
mcr       25
catA      24
ilvE      24
budC      23
pdc       23
cas       22
CUP1      22
arg       22
pflB      21
pyk       21
argF      21
pqo       20
TEM       20
xylAB     20
tef1      19
PKS       19
col       19
ble       18
PTM1      18
hsdR      18
aac       18
recA      18
araE      18
Name: count, dtype: int64

In [37]:
mauau = KEGG_id_list.dropna(subset=['KEGG_search'])

In [38]:
mauau.loc[mauau.loc[:,'index']==11].head(60)

,index,Genes,KEGG_search
183,11,"[JW0495, A0A0H2V720_A0A0H2YWH4_A0A237NDU1_A0A7...","[ecq:ECED1_0528, ecc:c0622, eum:ECUMN_0548, ec..."
184,11,"[JW1122, A0A080J239_A0A0D8VVE7_A0A0H2V8T7_A0A0...","[ecw:EcE24377A_1299, ecs:ECs_1608, ecm:EcSMS35..."
185,11,"[JW3536, A0A0E0XW32_A0A0H2VEL7_A0A0H2Z4X2_A0A0...","[ecv:APECO1_2885, ecc:c4384, ecj:JW3536, eco:b..."
186,11,"[JW3974, A0A061L2B2_A0A0H2VFL6_A0A0H2Z5T5_A0A0...","[ecc:c4971, eci:UTI89_C4573, ecx:EcHS_A4248, e..."
187,11,"[JW4364, A0A0E0Y423_A0A0H3EET3_A0A0H3MHN8_A0A1...","[ecx:EcHS_A0015, elh:ETEC_0013, eci:UTI89_C001..."
188,11,"[aceA, A0A080IF35_A0A0H2Z528_A0A0H3JR68_A0A0H3...","[ece:Z5601, ecg:E2348C_4318, ecm:EcSMS35_4469,..."
189,11,"[aceB, A0A061L2B2_A0A0H2VFL6_A0A0H2Z5T5_A0A0H3...","[ecc:c4971, eci:UTI89_C4573, ecx:EcHS_A4248, e..."
190,11,"[aceK, A0A061KYJ1_A0A0E0Y748_A0A0H3ENT7_A0A0H3...","[ecl:EcolC_4014, elo:EC042_4378, ece:Z5602, ec..."
191,11,"[ackA, A0A061KIF5_A0A0E0XXY6_A0A0H2VC85_A0A0H2...","[ecv:APECO1_4268, ecw:EcE24377A_2590, ecq:ECED..."
192,11,"[aldA, A0A024L3U1_A0A0H2V786_A0A0H2YYX6_A0A3L0...","[eci:UTI89_C1637, ecv:APECO1_566, elw:ECW_m154..."
193,11,"[araB, A0A0E0Y5I0_A0A0E0Y7K1_A0A0H3ECT0_A0A0H3...","[ecr:ECIAI1_0063, ect:ECIAI39_0066, ecf:ECH741..."
194,11,"[araD, A0A061KXT6_A0A0E0Y3Y4_A0A0H2V408_A0A0H2...","[ebd:ECBD_3556, ecw:EcE24377A_0063, elw:ECW_m0..."
195,11,"[arcA, A0A0E0Y423_A0A0H3EET3_A0A0H3MHN8_A0A140...","[ecx:EcHS_A0015, elh:ETEC_0013, eci:UTI89_C001..."
196,11,"[argF, A0A037YD56_A0A0H2Z5D9_A0A0H2Z630_A0A0H3...","[eck:EC55989_4812, ecc:c5353, ebd:ECBD_3782, e..."
197,11,"[eda, A0A080IXD6_A0A0H2YZU9_A0A0H3MFP5_A0A1M2I...","[ecc:c2263, elo:EC042_2017, ecv:APECO1_900, ec..."
198,11,"[edd, A0A0E0XYA5_A0A0H2VAA0_A0A0H2YZP1_A0A0H3E...","[ecj:JW1840, eco:b1851, ecm:EcSMS35_1336, ecg:..."
199,11,"[fucA, A0A037YR34_A0A0E0XWJ3_A0A0H2Z243_A0A0H3...","[elw:ECW_m3010, elh:ETEC_2990, eck:EC55989_307..."
200,11,"[fucK, A0A066T330_A0A0E0XYK4_A0A0H2Z1Y9_A0A0H3...","[ecm:EcSMS35_2944, ecj:JW2774, eco:b2803, ece:..."
201,11,"[galP, A0A0E1M1D1_A0A0H2Z379_A0A0H3MU82_A0A4P8...","[ecm:EcSMS35_3085, ecv:APECO1_3578, ecz:ECS88_..."
202,11,"[gcl, A0A0H2V720_A0A0H2YWH4_A0A237NDU1_A0A7M3S...","[ecq:ECED1_0528, ecc:c0622, eum:ECUMN_0548, ec..."
203,11,"[ghrA, A0A024L457_A0A0E0Y466_A0A0H3EI56_A0A140...","[ecc:c1295, ect:ECIAI39_2130, ecd:ECDH10B_1105..."
204,11,"[glcB, A0A080IR21_A0A0E0XUN3_A0A0H2Z2J0_A0A0H3...","[eum:ECUMN_3451, ecp:ECP_3053, ect:ECIAI39_346..."
205,11,"[glcD, A0A0H2Z2T0_A0A0H3MKF6_A0A7I6H955_A7ZRK7...","[ecc:c3709, ecq:ECED1_3622, ecx:EcHS_A3152, ec..."
206,11,"[icd, A0A080J239_A0A0D8VVE7_A0A0H2V8T7_A0A0H3M...","[ecw:EcE24377A_1299, ecs:ECs_1608, ecm:EcSMS35..."
207,11,"[iclR, A0A0E1M8Q8_A0A0H2VEL9_A0A0H2Z541_A0A0H3...","[ecz:ECS88_4482, eci:UTI89_C4576, ecs:ECs_4936..."
208,11,"[ilvG, A0A0H2VCU0_A0A0H2Z5D3_A0A0H3MJV6_A0A6M7...","[ecm:EcSMS35_4134, ecv:APECO1_2703, eci:UTI89_..."
210,11,"[lacZ, A0A024L722_A0A0E0Y4H0_A0A0H3EGE3_A0A0H3...","[ecm:EcSMS35_0375, ecl:EcolC_3281, ebd:ECBD_33..."
211,11,"[ldhA, A0A024L3A3_A0A0H2V7E7_A0A0H2YYN1_A0A0H3...","[ecc:c1827, elo:EC042_1527, eck:EC55989_1516, ..."
212,11,"[mgsA, A0A066Q245_A0A0E0Y165_A0A0H2YXU1_A0A0H3...","[esl:O3K_16525, eck:EC55989_1012, ecc:c1100, e..."
213,11,"[phoA, A0A0H2V6T6_A0A0H2YWC1_A0A0H3JCH7_A0A0H3...","[ecv:APECO1_1625, ect:ECIAI39_0298, ecj:JW0374..."
214,11,"[poxB, A0A0E0Y517_A0A0H2V5N4_A0A0H2YXK0_A0A0H3...","[ecj:JW0855, eco:b0871, elw:ECW_m0980, ece:Z11..."
215,11,"[pta, A0A080IUJ4_A0A0H2V9A8_A0A0H3MIG4_A0A5Q2E...","[ecc:c2840, elo:EC042_2538, ecg:E2348C_2437, e..."
217,11,"[rhaB, A0A066T5B3_A0A0E0Y5L9_A0A0H3EPJ6_A0A140...","[ebd:ECBD_4120, esl:O3K_24345, ect:ECIAI39_309..."
218,11,"[rhaD, A0A024L7K5_A0A0E0Y5V3_A0A0H3ENN9_A0A140...","[ecc:c4851, ecr:ECIAI1_4107, ect:ECIAI39_3095,..."
219,11,"[rph, A0A0E0XSS6_A0A0H3ENI9_A0A0H3MRK0_A0A140N...","[ecl:EcolC_0068, elw:ECW_m3919, ebw:BWG_3334, ..."
220,11,"[xylB, A0A0E0XW32_A0A0H2VEL7_A0A0H2Z4X2_A0A0H3...","[ecv:APECO1_2885, ecc:c4384, ecj:JW3536, eco:b..."
221,11,"[ycdW, A0A024L457_A0A0E0Y466_A0A0H3EI56_A0A140...","[ecc:c1295, ect:ECIAI39_2130, ecd:ECDH10B_1105..."
222,11,"[aceA, A0A8G0HNR2_P42449_Q6F5A3, cgj:AR0_11155...","[cgj:AR0_11155, cgq:CGLAR1_11005, cgb:cg2560, ..."
223,11,"[aceB, A0A0U4WVM8_A0A8G0CIY7_A4QG48_P42450A0A0...","[cgt:cgR_2211, cgb:cg2559, cgl:Cgl2329, cgt:cg..."
224,11,"[ackA, A0A0U4XXW1_A0A8G0CM61_A4QHF4_P77845, cg...","[cgb:cg3047, cgl:Cgl2752, cgx:SB89_12975, cgt:..."
227,11,"[argF, A0A0U4XV81_A0A8G0CI65_Q59283, cgb:cg158...","[cgb:cg1584, cgl:Cgl1398, cgj:AR0_07515, cgx:S..."
228,11,"[glcB, A0A0U4WVM8_A0A8G0CIY7_A4QG48_P42450A0A0...","[cgt:cgR_2211, cgb:cg2559, cgl:Cgl2329, cgt:cg..."
229,11,"[glcD, A0A8G0CKN4, cgj:AR0_11075;cgq:CGLAR1_10...","[cgj:AR0_11075, cgq:CGLAR1_10925]"
230,11,"[icd, A0A6L2RDW7_P50216, cgb:cg0766;cgl:Cgl0664;]","[cgb:cg0766, cgl:Cgl0664]"
232,11,"[pta, A0A8G0FXV7_A0A8G0HNP9_P77844, cgb:cg3048...","[cgb:cg3048, cgl:Cgl2753, cgj:AR0_13365, cgq:C..."
233,11,"[rph, A0A0U4XQD5_A0A1Q6BNN4_A4QGQ6_Q8NMR4A0A0U...","[cgj:AR0_12040, cgq:CGLAR1_11900, cgx:SB89_117..."
234,11,"[xylB, A0A0U4XS98_Q1JUZ0_Q8NU35, cgt:cgR_0188;...","[cgt:cgR_0188, cgl:Cgl0112]"

In [39]:
genes_kegg = mauau.KEGG_search.apply(buscar_magia)

In [40]:
mauau.loc[:,'New_genes']= genes_kegg

/var/folders/v6/y2v6wwn93yj5vvhl558fx2zc0000gn/T/ipykernel_65240/750895937.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mauau.loc[:,'New_genes']= genes_kegg

In [41]:
mauau = mauau.dropna(subset=['New_genes'])

In [42]:
mauau = mauau.loc[:,['index','New_genes']]

In [43]:
mauau = mauau.drop_duplicates()

In [44]:
mauau = mauau.groupby('index').agg(list)

In [45]:
mauau

                                               New_genes
index
3      [K02341, K00975, K02634, K02703, K08139, K0061...
4      [K02550, K00853, K03077, K01150, K00849, K0096...
5      [K00688, K01214, K04751, K00033, K00626, K0002...
7                                               [K22894]
9                       [K13950, K01092, K00794, K00793]
...                                                  ...
10690  [K13953, K00968, K14686, K08738, K00511, K0062...
10693                                           [K00844]
10695                                           [K14338]
10697                   [K13498, K10884, K01609, K09467]
10699                                   [K00558, K13632]

[4536 rows x 1 columns]

In [46]:
mauau

                                               New_genes
index
3      [K02341, K00975, K02634, K02703, K08139, K0061...
4      [K02550, K00853, K03077, K01150, K00849, K0096...
5      [K00688, K01214, K04751, K00033, K00626, K0002...
7                                               [K22894]
9                       [K13950, K01092, K00794, K00793]
...                                                  ...
10690  [K13953, K00968, K14686, K08738, K00511, K0062...
10693                                           [K00844]
10695                                           [K14338]
10697                   [K13498, K10884, K01609, K09467]
10699                                   [K00558, K13632]

[4536 rows x 1 columns]

In [47]:
org_prod.head()

,Title,PM_ID,Abstract,Journal,Year,PMC_ID,DOI,Type,Author,Classification,Text,Abstract_min,Title_min,Full_text_min,Old_name,Organism,Genes
0,Biosynthesis of a Novel Bioactive Metabolite o...,33356220,Spermidine is a biologically active polyamine ...,Journal of agricultural and food chemistry,2021,NaN,10.1021/acs.jafc.0c07143,"Journal Article,","[ForeName:Dian,LastName:Zou] [ForeName:Lu,Last...",1,None,Spermidine polyamine application foods. Howeve...,Biosynthesis Novel Bioactive Metabolite Spermi...,,[Bacillus amyloliquefaciens],[Bacillus amyloliquefaciens],"[[speD, A0A4V7TT54, 0], [speE, A0A1Y0XKU0, 0]]"
1,Engineering a glycerol utilization pathway in ...,27395064,To explore the glycerol utilization pathway in...,Biotechnology letters,2016,NaN,10.1007/s10529-016-2166-4,"Journal Article,","[ForeName:Chen,LastName:Wang] [ForeName:Heng,L...",1,None,explore glycerol utilization pathway Corynebac...,Engineering glycerol utilization pathway Coryn...,,[Corynebacterium glutamicum],[Corynebacterium glutamicum],None
2,Systematic single-cell analysis of Komagataell...,22685548,Biopharmaceuticals represent the fastest growi...,PloS one,2012,3369916.0,10.1371/journal.pone.0037915,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:Kerry Routenberg,LastName:Love] [For...",1,\n Introduction \n More than 240 m...,Biopharmaceuticals represent sector industry. ...,Systematic single-cell analysis Komagataella p...,Introduction 240 antibody products trials [1] ...,[Komagataella pastoris],[Komagataella pastoris],None
3,Metabolic Engineering and Comparative Performa...,26732758,Wood sugars such as xylose can be used as an i...,Frontiers in microbiology,2015,4689873.0,10.3389/fmicb.2015.01484,"Journal Article,","[ForeName:Saurabh,LastName:Ranade] [ForeName:Y...",1,\n Introduction \n Lignocellulosic...,Wood sugars xylose carbon source biotechnologi...,Metabolic Engineering Comparative Performance ...,"Introduction Lignocellulosic abundant, inexpen...",[Synechocystis PCC],[Synechocystis PCC],"[[and, P73507_P74389, syn:slr0446;syn:sll1360;..."
4,Improving D-glucaric acid production from myo-...,24333274,D-glucaric acid has been explored for a myriad...,Metabolic engineering,2014,NaN,10.1016/j.ymben.2013.12.002,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:Eric,LastName:Shiue] [ForeName:Krist...",1,Metabolic Engineering 22 (2014) 22–31\n\nConte...,"D-glucaric explored uses, including biopolymer...",Improving D-glucaric production myo-inositol E...,Metabolic Engineering (2014) 22–31 Contents li...,[E coli],[Escherichia coli],"[[JW1087, A0A066RFP3_A0A0H2YXQ2_A0A0H3MHP8_A0A..."

In [48]:
org_prod.index.name='index'

In [49]:
org_prod =org_prod.rename(columns={'Genes':'old_genes'})

In [50]:
org_prod = pd.concat([org_prod,mauau],axis=1)

In [51]:
org_prod.head()

,Title,PM_ID,Abstract,Journal,Year,PMC_ID,DOI,Type,Author,Classification,Text,Abstract_min,Title_min,Full_text_min,Old_name,Organism,old_genes,New_genes
index,,,,,,,,,,,,,,,,,,
0,Biosynthesis of a Novel Bioactive Metabolite o...,33356220,Spermidine is a biologically active polyamine ...,Journal of agricultural and food chemistry,2021,NaN,10.1021/acs.jafc.0c07143,"Journal Article,","[ForeName:Dian,LastName:Zou] [ForeName:Lu,Last...",1,None,Spermidine polyamine application foods. Howeve...,Biosynthesis Novel Bioactive Metabolite Spermi...,,[Bacillus amyloliquefaciens],[Bacillus amyloliquefaciens],"[[speD, A0A4V7TT54, 0], [speE, A0A1Y0XKU0, 0]]",NaN
1,Engineering a glycerol utilization pathway in ...,27395064,To explore the glycerol utilization pathway in...,Biotechnology letters,2016,NaN,10.1007/s10529-016-2166-4,"Journal Article,","[ForeName:Chen,LastName:Wang] [ForeName:Heng,L...",1,None,explore glycerol utilization pathway Corynebac...,Engineering glycerol utilization pathway Coryn...,,[Corynebacterium glutamicum],[Corynebacterium glutamicum],None,NaN
2,Systematic single-cell analysis of Komagataell...,22685548,Biopharmaceuticals represent the fastest growi...,PloS one,2012,3369916.0,10.1371/journal.pone.0037915,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:Kerry Routenberg,LastName:Love] [For...",1,\n Introduction \n More than 240 m...,Biopharmaceuticals represent sector industry. ...,Systematic single-cell analysis Komagataella p...,Introduction 240 antibody products trials [1] ...,[Komagataella pastoris],[Komagataella pastoris],None,NaN
3,Metabolic Engineering and Comparative Performa...,26732758,Wood sugars such as xylose can be used as an i...,Frontiers in microbiology,2015,4689873.0,10.3389/fmicb.2015.01484,"Journal Article,","[ForeName:Saurabh,LastName:Ranade] [ForeName:Y...",1,\n Introduction \n Lignocellulosic...,Wood sugars xylose carbon source biotechnologi...,Metabolic Engineering Comparative Performance ...,"Introduction Lignocellulosic abundant, inexpen...",[Synechocystis PCC],[Synechocystis PCC],"[[and, P73507_P74389, syn:slr0446;syn:sll1360;...","[K02341, K00975, K02634, K02703, K08139, K0061..."
4,Improving D-glucaric acid production from myo-...,24333274,D-glucaric acid has been explored for a myriad...,Metabolic engineering,2014,NaN,10.1016/j.ymben.2013.12.002,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:Eric,LastName:Shiue] [ForeName:Krist...",1,Metabolic Engineering 22 (2014) 22–31\n\nConte...,"D-glucaric explored uses, including biopolymer...",Improving D-glucaric production myo-inositol E...,Metabolic Engineering (2014) 22–31 Contents li...,[E coli],[Escherichia coli],"[[JW1087, A0A066RFP3_A0A0H2YXQ2_A0A0H3MHP8_A0A...","[K02550, K00853, K03077, K01150, K00849, K0096..."

In [46]:
org_prod.New_genes.dropna()

index
24       [K02550, K00853, K03077, K01150, K01146, K0084...
39                                                [K22894]
48                        [K13950, K01092, K00794, K00793]
55       [K11262, K01067, K01895, K00856, K14171, K0012...
64       [K01608, K00031, K00854, K01638, K04043, K0163...
                               ...
89926    [K13954, K00002, K14171, K00004, K01697, K0084...
89971    [K13953, K00968, K14686, K08738, K00511, K0062...
89993                                             [K00844]
90015                     [K10884, K13498, K01609, K09467]
90055                                     [K00558, K13632]
Name: New_genes, Length: 3845, dtype: object

In [52]:
org_prod.New_genes.dropna()

index
3        [K02341, K00975, K02634, K02703, K08139, K0061...
4        [K02550, K00853, K03077, K01150, K00849, K0096...
5        [K00688, K01214, K04751, K00033, K00626, K0002...
7                                                 [K22894]
9                         [K13950, K01092, K00794, K00793]
                               ...
10690    [K13953, K00968, K14686, K08738, K00511, K0062...
10693                                             [K00844]
10695                                             [K14338]
10697                     [K13498, K10884, K01609, K09467]
10699                                     [K00558, K13632]
Name: New_genes, Length: 4536, dtype: object

In [53]:
org_prod =org_prod.rename(columns={'New_genes':'Genes'})

In [54]:
org_prod.Genes.dropna()

index
3        [K02341, K00975, K02634, K02703, K08139, K0061...
4        [K02550, K00853, K03077, K01150, K00849, K0096...
5        [K00688, K01214, K04751, K00033, K00626, K0002...
7                                                 [K22894]
9                         [K13950, K01092, K00794, K00793]
                               ...
10690    [K13953, K00968, K14686, K08738, K00511, K0062...
10693                                             [K00844]
10695                                             [K14338]
10697                     [K13498, K10884, K01609, K09467]
10699                                     [K00558, K13632]
Name: Genes, Length: 4536, dtype: object

In [55]:
check_save_file(org_prod, 'Full_text_KEGG_genes_24_test.json', 'Articles')

Saved file in: /Users/elisamarquez/Documents/PhD/2semestre/Engineering_db/Engineering_db/files/Output/Articles/Full_text_KEGG_genes_24_test.json

In [56]:
org_prod

,Title,PM_ID,Abstract,Journal,Year,PMC_ID,DOI,Type,Author,Classification,Text,Abstract_min,Title_min,Full_text_min,Old_name,Organism,old_genes,Genes
index,,,,,,,,,,,,,,,,,,
0,Biosynthesis of a Novel Bioactive Metabolite o...,33356220,Spermidine is a biologically active polyamine ...,Journal of agricultural and food chemistry,2021,NaN,10.1021/acs.jafc.0c07143,"Journal Article,","[ForeName:Dian,LastName:Zou] [ForeName:Lu,Last...",1,None,Spermidine polyamine application foods. Howeve...,Biosynthesis Novel Bioactive Metabolite Spermi...,,[Bacillus amyloliquefaciens],[Bacillus amyloliquefaciens],"[[speD, A0A4V7TT54, 0], [speE, A0A1Y0XKU0, 0]]",NaN
1,Engineering a glycerol utilization pathway in ...,27395064,To explore the glycerol utilization pathway in...,Biotechnology letters,2016,NaN,10.1007/s10529-016-2166-4,"Journal Article,","[ForeName:Chen,LastName:Wang] [ForeName:Heng,L...",1,None,explore glycerol utilization pathway Corynebac...,Engineering glycerol utilization pathway Coryn...,,[Corynebacterium glutamicum],[Corynebacterium glutamicum],None,NaN
2,Systematic single-cell analysis of Komagataell...,22685548,Biopharmaceuticals represent the fastest growi...,PloS one,2012,3369916.0,10.1371/journal.pone.0037915,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:Kerry Routenberg,LastName:Love] [For...",1,\n Introduction \n More than 240 m...,Biopharmaceuticals represent sector industry. ...,Systematic single-cell analysis Komagataella p...,Introduction 240 antibody products trials [1] ...,[Komagataella pastoris],[Komagataella pastoris],None,NaN
3,Metabolic Engineering and Comparative Performa...,26732758,Wood sugars such as xylose can be used as an i...,Frontiers in microbiology,2015,4689873.0,10.3389/fmicb.2015.01484,"Journal Article,","[ForeName:Saurabh,LastName:Ranade] [ForeName:Y...",1,\n Introduction \n Lignocellulosic...,Wood sugars xylose carbon source biotechnologi...,Metabolic Engineering Comparative Performance ...,"Introduction Lignocellulosic abundant, inexpen...",[Synechocystis PCC],[Synechocystis PCC],"[[and, P73507_P74389, syn:slr0446;syn:sll1360;...","[K02341, K00975, K02634, K02703, K08139, K0061..."
4,Improving D-glucaric acid production from myo-...,24333274,D-glucaric acid has been explored for a myriad...,Metabolic engineering,2014,NaN,10.1016/j.ymben.2013.12.002,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:Eric,LastName:Shiue] [ForeName:Krist...",1,Metabolic Engineering 22 (2014) 22–31\n\nConte...,"D-glucaric explored uses, including biopolymer...",Improving D-glucaric production myo-inositol E...,Metabolic Engineering (2014) 22–31 Contents li...,[E coli],[Escherichia coli],"[[JW1087, A0A066RFP3_A0A0H2YXQ2_A0A0H3MHP8_A0A...","[K02550, K00853, K03077, K01150, K00849, K0096..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10695,Optimisation of Cytochrome P450 BM3 Assisted b...,33860879,Cytochrome P450 enzymes have attracted much in...,Applied biochemistry and biotechnology,2021,NaN,10.1007/s12010-021-03573-1,"Journal Article,","[ForeName:Thierry,LastName:Vincent] [ForeName:...",1,None,Cytochrome P450 enzymes attracted interest yea...,Optimisation Cytochrome P450 BM3 Assisted Cons...,,[Priestia megaterium],[Priestia megaterium],"[[CYP102A1, P14779, bmeg:BG04_163;]]",[K14338]
10696,CRISPR-Cas9-enabled genetic disruptions for un...,28652865,The thermotolerant yeast <i>Kluyveromyces marx...,Biotechnology for biofuels,2017,5483312.0,10.1186/s13068-017-0854-5,"Journal Article,","[ForeName:Ann-Kathrin,LastName:Löbs] [ForeName...",1,\n Background \n The yeast Kluyve...,thermotolerant yeast <i>Kluyveromyces marxianu...,CRISPR-Cas9-enabled disruptions ethanol ethyl ...,Background yeast Kluyveromyces marxianus host ...,[Kluyveromyces marxianus],[Kluyveromyces marxianus],"[[ADH1, Q07288, 0], [ADH2, Q9P4C2, 0], [ADH3, ...",NaN
10697,Development of a genome-editing CRISPR/Cas9 sy...,28053662,"Over the past 3 years, the CRISPR/Cas9 system ...",Biotechnology for biofuels,2017,5209885.0,10.1186/s13068-016-0693-9,"Journal Article,","[ForeName:Qian,LastName:Liu] [ForeName:Ranran,...",1,\n Background \n Lignocellulosic b...,"years, CRISPR/Cas9 system revolutionized field...",Development genome-editing CRISPR/Cas9 system ...,"Background Lignocellulosic biomass renewable, ...","[Neurospora crassa, Trichoderma reesei, Escher...","[Saccharomyces cerevisiae, Escherichia coli, N...","[[cre, A0A0E1M686, 0], [neo, P00551_Q79DX9, ag...","[K13498, K10884, K01609, K09467]"
10698,Development of versatile and efficient genetic...,35043238,Marine-derived Aspergillus terreus produces a ...,Current genetics,2022,NaN,10.1007/s00294-021-01218-8,"Journal Article,","[ForeName:Guangshan,LastName:Yao] [ForeName:Xi...",1,None,Marine-derived Aspergillus terreus produces va...,Development tools marine-derived fungus Asperg...,,[Aspergillus terreus],[Aspergillus terreus],"[[laeA, A0A1V0FZV9, 0]]",NaN
10699,Improving phloroglucinol tolerance and product...,29258595,Phloroglucinol is an important chemical which ...,Microbial cell factories,2017,5735909.0,10.1186/s12934-017-0839-x,"Journal Article,","[ForeName:Rubing,LastName:Zhang] [ForeName:Yuj...",1,\n Background \n Phloroglucinol an...,Phloroglucinol produced engineered Escherichia...,Improving phloroglucinol tolerance production ...,Background Phloroglucinol derivatives pharmace...,[Escherichia coli],[Escherichia coli],"[[DnaJ, M1EZQ5, 0], [dcm, A0A066SWY3_A0A0F3TQQ...","[K00558, K13632]"

In [46]:
sum(org_prod.PMC_ID != 'None')

3869