In [1]:
import scrapy
print(scrapy.__version__)

2.4.1

In [2]:
import os
os.environ['UNPAYWALL_EMAIL'] = 'elisa.m.zavala@ntnu.no'
from unpywall import Unpywall

In [9]:
import unpywall

In [17]:
unpywall.Unpywall

unpywall.Unpywall

In [ ]:
import PyPaperBot
import sys
sys.path.append('../')
sys.path.append('../..')
sys.path.append('../../02_Classify_articles/')

from file_management import get_files_dir,check_save_file
_, INPUT_DIR, OUTPUT_DIR = get_files_dir()

from extract_NCBI import *
from retrieve_full_text import *

In [3]:
import os
os.environ['UNPAYWALL_EMAIL'] = 'elisa.m.zavala@ntnu.no'
from unpywall import Unpywall

In [4]:
import pandas as pd
import numpy as np

In [5]:
from Bio import Entrez

Entrez.email = "elisa.m.zavala@ntnu.no"

In [6]:
file = OUTPUT_DIR+'/Articles/classified_articles_v_2025_06_30.csv'
classified_data = pd.read_csv(file)
classified_data.PMC_ID = classified_data.PMC_ID.replace('None', np.nan)
print(classified_data.shape)
classified_data = classified_data.loc[~classified_data.Type.str.lower().str.contains('review')]
print(classified_data.shape)

(20108, 12)
(16271, 12)

# Get full text from PMC

In [7]:
import OpenSSL
print(OpenSSL.__version__)

22.0.0

import sys

from twisted.internet import asyncioreactor
asyncioreactor.install()

In [8]:
classified_data

,Unnamed: 0.1,Unnamed: 0,PM_ID,Title,Abstract,Journal,Year,PMC_ID,DOI,Type,Author,Classification
0,13,13,10618204,Increased production of zeaxanthin and other p...,The psbAII locus was used as an integration pl...,Applied and environmental microbiology,2000.0,91786.0,10.1128/AEM.66.1.64-72.2000,"Journal Article,Research Support, U.S. Gov't, ...","[ForeName:D,LastName:Lagarde] [ForeName:L,Last...",1
1,14,14,10618209,Expression of Alcaligenes eutrophus flavohemop...,Expression of the vhb gene encoding hemoglobin...,Applied and environmental microbiology,2000.0,91791.0,10.1128/AEM.66.1.98-104.2000,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:A D,LastName:Frey] [ForeName:J E,Las...",1
2,31,31,10631776,Environmental biotechnology.,There is an increasing interest in environment...,Trends in biotechnology,2000.0,NaN,10.1016/s0167-7799(99)01399-2,"Journal Article,","[ForeName:L P,LastName:Wackett]",1
3,50,50,10649237,Altered regulation of pyruvate kinase or co-ov...,Glycolytic fluxes in resting Escherichia coli ...,Biotechnology and bioengineering,2000.0,NaN,10.1002/(sici)1097-0290(20000305)67:5<623::aid...,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:M,LastName:Emmerling] [ForeName:J E,...",1
4,51,51,10649449,Cloning and characterization of the Yarrowia l...,The squalene synthase (SQS) gene encodes a key...,"Yeast (Chichester, England)",2000.0,NaN,10.1002/(SICI)1097-0061(200002)16:3<197::AID-Y...,"Journal Article,Research Support, Non-U.S. Gov...","[ForeName:S,LastName:Merkulov] [ForeName:F,Las...",1
...,...,...,...,...,...,...,...,...,...,...,...,...
20102,152913,152913,40572208,Heterologous Expression of the Nitrogen-Fixing...,Microbially mediated biological nitrogen fixat...,Microorganisms,2025.0,12195393.0,10.3390/microorganisms13061320,"Journal Article,","[ForeName:Xiuling,LastName:Wang] [ForeName:Shi...",1
20104,152927,152927,40573728,Functional Characterization of Squalene Epoxid...,The medicinal plant <i>Siraitia grosvenorii</i...,"Plants (Basel, Switzerland)",2025.0,NaN,10.3390/plants14121740,"Journal Article,","[ForeName:Huan,LastName:Zhao] [ForeName:Ze,Las...",1
20105,152973,152973,40577193,Structural characterization and dynamics of Ad...,"<i>Clostridium thermocellum</i>, a cellulolyti...",eLife,2025.0,NaN,10.7554/eLife.96966,"Journal Article,","[ForeName:Samantha J,LastName:Ziegler] [ForeNa...",1
20106,152993,152993,40578703,Overcoming glucose repression through cellobio...,Pectin-rich biomass is a promising substrate f...,Bioresource technology,2025.0,NaN,10.1016/j.biortech.2025.132892,"Journal Article,","[ForeName:Dahye,LastName:Lee] [ForeName:Deokye...",1
20107,152997,152997,40579636,Genetically engineering central carbon and nit...,Poly-γ-glutamic acid (γ-PGA) is a biopolymer w...,World journal of microbiology & biotechnology,2025.0,NaN,10.1007/s11274-025-04467-8,"Journal Article,","[ForeName:Jishuai,LastName:Qi] [ForeName:Rui,L...",1

In [9]:
# Get the full text
pmc_ids = classified_data.PMC_ID.dropna()
pmc_ids = pmc_ids.apply(str).to_list()
#full_text = get_PMC_full_text(pmc_ids)

In [10]:
multiple_urls = get_PMC_scrappy_url(pmc_ids,scrapy_url=True)

INFO - Fetching batch 1/15 (Attempt 1)
INFO - Fetching batch 2/15 (Attempt 1)
INFO - Fetching batch 3/15 (Attempt 1)
INFO - Fetching batch 4/15 (Attempt 1)
INFO - Fetching batch 5/15 (Attempt 1)
INFO - Fetching batch 6/15 (Attempt 1)
INFO - Fetching batch 7/15 (Attempt 1)
INFO - Fetching batch 8/15 (Attempt 1)
INFO - Fetching batch 9/15 (Attempt 1)
INFO - Fetching batch 10/15 (Attempt 1)
INFO - Fetching batch 11/15 (Attempt 1)
INFO - Fetching batch 12/15 (Attempt 1)
INFO - Fetching batch 13/15 (Attempt 1)
INFO - Fetching batch 14/15 (Attempt 1)
INFO - Fetching batch 15/15 (Attempt 1)

In [11]:
    text_batches = []
    for url in multiple_urls.values():
        #text_obtained = get_PMC_full_text_url(url, False, False)
        text_obtained = get_PMC_full_text_url(url, True, True)
        text_obtained.index = text_obtained.index.astype(int)
        text_batches.append(text_obtained)
       
    full_text = pd.concat(text_batches).dropna()

In [12]:
full_text

,Text,Org_Gene
11934354,"{'Section_0': ['Background', 'Fruit-set and gr...","{'Section_0': ['DefH9-iaaM', 'iaaM', 'Pseudomo..."
15588323,"{'Section_0': ['Introduction', 'The souring of...","{'Section_0': ['Lactococcus lactis', 'L. lacti..."
12620118,"{'Section_0': ['Background', 'Drosophila melan...","{'Section_0': ['Drosophila melanogaster ', 'Dr..."
15341664,"{'Section_0': ['Background', 'The combinatoria...","{'Section_0': ['in vitro '], 'Section_1': ['F ..."
15904518,"{'Section_0': ['Review', 'Metabolic engineerin...","{'Section_0': ['Escherichia coli ', 'E. coli',..."
...,...,...
40559434,"{'Section_0': ['1. Introduction', 'Escherichia...","{'Section_0': ['Escherichia coli', 'Salmonella..."
40529627,"{'Section_0': ['1', 'Introduction', 'The genus...","{'Section_0': ['Streptomyces', 'via', 'Strepto..."
40510666,"{'Section_0': ['1', 'Introduction', 'Cheese is...","{'Section_0': ['α', 'β', 'κ', 'κ', 'Escherichi..."
40493205,"{'Section_0': ['Introduction', 'Ergothioneine ...","{'Section_0': ['Claviceps purpurea', 'EgtABCDE..."
40503443,"{'Section_0': ['Abbreviations:', 'MVA', 'meval...","{'Section_0': [], 'Section_1': ['Saccharomyces..."

In [13]:
full_text.Text

11934354    {'Section_0': ['Background', 'Fruit-set and gr...
15588323    {'Section_0': ['Introduction', 'The souring of...
12620118    {'Section_0': ['Background', 'Drosophila melan...
15341664    {'Section_0': ['Background', 'The combinatoria...
15904518    {'Section_0': ['Review', 'Metabolic engineerin...
                                  ...
40559434    {'Section_0': ['1. Introduction', 'Escherichia...
40529627    {'Section_0': ['1', 'Introduction', 'The genus...
40510666    {'Section_0': ['1', 'Introduction', 'Cheese is...
40493205    {'Section_0': ['Introduction', 'Ergothioneine ...
40503443    {'Section_0': ['Abbreviations:', 'MVA', 'meval...
Name: Text, Length: 5967, dtype: object

In [14]:
import re

# Improved marker phrases with regex patterns
marker_patterns = [
    r'^The present (?:study|work|report|manuscript|paper|research|investigation|article)\b',
    r'^In this (?:study|work|report|paper|research|investigation|article)\b',
    r'^This (?:study|work|report|paper|research|investigation|article)\b',
    r'^In the present (?:study|work|report|manuscript|paper|research|investigation|article)\b',
    r'^In the current (?:study|work|report|manuscript|paper|research|investigation|article)\b',
    r'^The aim of this (?:study|work|report|manuscript|paper|research|investigation|article)\b',
    r'^The purpose of this (?:study|work|report|manuscript|paper|research|investigation|article)\b',
    r'^The goal of this (?:study|work|report|manuscript|paper|research|investigation|article)\b',
    r'^Our (?:study|work|report|manuscript|paper|research|investigation|article)\b(?:used|employed|showed)\b',
    r'^We (?:used|employed|showed|investigated|present|report)\b',
    r'^It was (?:thus|therefore) our goal\b',
    r'^This (?:study|work|report|manuscript|paper|research|investigation|article) (?:was|is)\b',
    r'^Therefore, in this (?:study|work|report|manuscript|paper|research|investigation|article)\b',
    r'^Thus, in this (?:study|work|report|manuscript|paper|research|investigation|article)\b',

    r'^Here we\b',
    r'^Here, we\b',
    r'^The research reported here\b',
    r'^Inspired by this work, we\b',
    r'^Based on the (?:above )?reasons, we\b',
    r'^Herein,\b',
    r'^Recently, we\b',
    # Expanded verb patterns
    r'^We (?:describe|discuss|examine|analyze|present|investigate|report|show)\b',

]
# Compile patterns for better performance
compiled_patterns = [re.compile(pattern, re.IGNORECASE) for pattern in marker_patterns]

In [15]:

def get_first_clean_word(text):
    text = re.sub(r'^([IVXLCDM]+)\.', 
                 lambda m: str(sum(1 for _ in m.group(1))) + '.', 
                 text,
                 flags=re.IGNORECASE)
    clean_start = re.sub(r'^[^a-zA-Z]*', '', text.lower())
    first_word = clean_start.split()[0] if clean_start else ""
    return re.sub(r'[^a-zA-Z]', '', first_word)

def process_introduction_section(section_content, compiled_patterns, section_starters):
    """Processes a section to extract relevant introduction content."""
    # Check if section qualifies as introduction
    first_word = get_first_clean_word(section_content[0])
    valid_section = first_word in section_starters
    
    if len(section_content) > 1 and not valid_section:
        second_word = get_first_clean_word(section_content[1])
        valid_section = second_word in section_starters
    
    if not valid_section:
        return None
    
    # Process the content
    new_text = ''.join(section_content)
    cleaned_text = re.sub(r'\.\s+', '.', new_text)
    
    # Split sentences
    sentences = []
    start = 0
    for boundary in [m.start() for m in re.finditer(r'\.([A-Z])', cleaned_text)]:
        sentences.append(cleaned_text[start:boundary+1])
        start = boundary + 1
    sentences.append(cleaned_text[start:])
    
    # Find first marker sentence
    start_index = None
    for i, sentence in enumerate(sentences):
        if any(pattern.match(sentence.strip()) for pattern in compiled_patterns):
            start_index = i
            break
    
    # Get relevant sentences
    if start_index is not None:
        relevant_sentences = sentences[start_index:]
    else:
        relevant_sentences = sentences[-6:] if len(sentences) >= 6 else sentences
    
    return ' '.join(relevant_sentences)

In [16]:

# Main processing
section_starters = ['background', 'introduction', 'review', 'introdution']
new_values = {}

for idx, sections in full_text.Text.items():
    result = process_introduction_section(
        sections['Section_0'],
        compiled_patterns,
        section_starters
    )
    
    if result is not None:
        new_values[idx] = result
    else:
        first_word = get_first_clean_word(sections['Section_0'][0])
        print(f"Section not matched: {first_word}\nFull section start:\n{sections['Section_0'][0]}\n")

Section not matched: experimental
Full section start:
EXPERIMENTAL PROCEDURES

Section not matched: supplementary
Full section start:
Supplementary Material

Section not matched: results
Full section start:
Results and Discussion

Section not matched: biofilms
Full section start:
Biofilms and pathogens

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched:
Full section start:
1.

Section not matched: results
Full section start:
Results

Section not matched: materials
Full section start:
Materials and Methods

Section not matched: results
Full section start:
Results

Section not matched: materials
Full section start:
Materials and Methods

Section not matched: online
Full section start:
ONLINE METHODS

Section not matched: nannochloropsis
Full section start:
Nannochloropsis for Biofuel Production

Section not matched: results
Full section start:
Results

Section not matched: commentary
Full section start:
Commentary

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: results
Full section start:
Results

Section not matched: genome
Full section start:
Genome sequencing, assembly, annotation and bioinformatic analysis

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: results
Full section start:
Results

Section not matched: construction
Full section start:
Construction
of Synthetic Core Promoter pCore11

Section not matched: results
Full section start:
Results

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: methods
Full section start:
Methods

Section not matched: results
Full section start:
Results and Discussion

Section not matched: materials
Full section start:
Materials and Methods

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: results
Full section start:
Results and Discussion

Section not matched: results
Full section start:
Results
and Discussion

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: methods
Full section start:
Methods

Section not matched: commentary
Full section start:
COMMENTARY

Section not matched: materials
Full section start:
Materials and Methods

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: results
Full section start:
Results and Discussion

Section not matched: results
Full section start:
Results

Section not matched: materials
Full section start:
Materials and Methods

Section not matched: methods
Full section start:
Methods

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results and Discussion

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched:
Full section start:
1

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: materials
Full section start:
Materials and Methods

Section not matched: results
Full section start:
Results

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: experimental
Full section start:
Experimental Section

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results and Discussion

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results
and Discussion

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results and discussion

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results and Discussion

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results and Discussion

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: some
Full section start:
SOME HISTORY

Section not matched: results
Full section start:
Results

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: specifications
Full section start:
Specifications

Section not matched: results
Full section start:
Results and Discussion

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: methods
Full section start:
Methods

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results and Discussion

Section not matched: results
Full section start:
Results and Discussion

Section not matched: erratum
Full section start:
Erratum to: Biotechnol Biofuels (2016) 9:58 DOI 10.1186/s13068-016-0466-5

Section not matched: results
Full section start:
Results

Section not matched: methods
Full section start:
Methods

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: supporting
Full section start:
Supporting Information

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results and Discussion

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results and Discussion

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: results
Full section start:
Results

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: methods
Full section start:
Methods

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results and Discussion

Section not matched: results
Full section start:
Results

Section not matched: materials
Full section start:
Materials and Methods

Section not matched: results
Full section start:
Results and Discussion

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results and Discussion

Section not matched: genome
Full section start:
GENOME ANNOUNCEMENT

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: materials
Full section start:
Materials and Methods

Section not matched: results
Full section start:
Results

Section not matched: materials
Full section start:
Materials and Methods

Section not matched: results
Full section start:
Results and Discussion

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched:
Full section start:
1

Section not matched: results
Full section start:
Results

Section not matched: conflict
Full section start:
Conflict of interest

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: fulltext
Full section start:
Full-Text

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: conflict
Full section start:
Conflict of interest

Section not matched: author
Full section start:
Author contributions

Section not matched: construction
Full section start:
Construction of tailor‐made bacteria by genome engineering

Section not matched: conflict
Full section start:
Conflict of interest

Section not matched: results
Full section start:
Results

Section not matched:
Full section start:



Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: the
Full section start:
THE PftAB COMPLEX FROM

Section not matched: results
Full section start:
Results

Section not matched: online
Full section start:
ONLINE METHODS

Section not matched: conflict
Full section start:
Conflict of interest

Section not matched: results
Full section start:
Results

Section not matched: retraction
Full section start:
Retraction to: Biotechnol Biofuels (2017) 10:235 10.1186/s13068-017-0920-z

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: experimental
Full section start:
Experimental Section

Section not matched: results
Full section start:
Results

Section not matched: change
Full section start:
1. Change in Main Body Paragraph

Section not matched: abbreviations
Full section start:
Abbreviations

Section not matched: results
Full section start:
RESULTS

Section not matched: results
Full section start:
Results

Section not matched: conflict
Full section start:
Conflict of interest statement

Section not matched: conflict
Full section start:
Conflict of interest

Section not matched: conflict
Full section start:
Conflict of interest

Section not matched: mining
Full section start:
Mining available genomes

Section not matched: results
Full section start:
Results
and Discussion

Section not matched: results
Full section start:
Results

Section not matched: abbreviations
Full section start:
Abbreviations

Section not matched: results
Full section start:
Results

Section not matched: notice
Full section start:
Notice of republication

Section not matched: results
Full section start:
Results

Section not matched: the
Full section start:
The choice engineering competition

Section not matched: abbreviations
Full section start:
ABBREVIATIONS

Section not matched: results
Full section start:
Results and Discussion

Section not matched: results
Full section start:
Results and Discussion

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results
and Discussion

Section not matched: highlights
Full section start:
Highlights

Section not matched: results
Full section start:
Results and Discussion

Section not matched: materials
Full section start:
Materials and Methods

Section not matched: supplemental
Full section start:
Supplemental Materials

Section not matched: abbreviations
Full section start:
Abbreviations

Section not matched: conflict
Full section start:
Conflict of interest

Section not matched: commentary
Full section start:
COMMENTARY

Section not matched:
Full section start:



Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results
and Discussion

Section not matched: key
Full section start:
Key points

Section not matched: materials
Full section start:
Materials and methods

Section not matched: conflict
Full section start:
Conflict of interest

Section not matched: online
Full section start:
Online methods

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: metabolic
Full section start:
Metabolic engineering of lipid metabolism

Section not matched: supplementary
Full section start:
Supplementary Data

Section not matched: keypoints
Full section start:
Keypoints

Section not matched: materials
Full section start:
Materials and Methods

Section not matched: declaration
Full section start:
Declaration of competing interest

Section not matched: results
Full section start:
Results and Discussions

Section not matched: results
Full section start:
Results and Discussion

Section not matched: backgrounds
Full section start:
Backgrounds

Section not matched: experimental
Full section start:
Experimental Section

Section not matched: results
Full section start:
Results

Section not matched: yeast
Full section start:
Yeast Grows Faster in Rich Medium under Both Aerobic and Anaerobic Growth Conditions

Section not matched: results
Full section start:
Results
and Discussion

Section not matched: findings
Full section start:
Findings

Section not matched: ta
Full section start:
TA acyl acceptor and donor biosynthesis

Section not matched: abbreviations
Full section start:
Abbreviations:

Section not matched: accession
Full section start:
Accession number

Section not matched: results
Full section start:
Results
and Discussion

Section not matched: list
Full section start:
List of abbreviations

Section not matched: the
Full section start:
The driver: synthetic biology in higher eukaryotes is slow and difficult

Section not matched: conflict
Full section start:
Conflict of interest

Section not matched: abbreviations
Full section start:
ABBREVIATIONS

Section not matched: correction
Full section start:
Correction to: Biotechnol Biofuels (2020) 13:176

Section not matched: specifications
Full section start:
Specifications Table

Section not matched: abbreviations
Full section start:
Abbreviations

Section not matched: materials
Full section start:
Materials and methods

Section not matched: key
Full section start:
Key points

Section not matched: results
Full section start:
Results and Discussion

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: conflict
Full section start:
Conflict of interest

Section not matched: highlight
Full section start:
Highlight

Section not matched: key
Full section start:
Key points

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: key
Full section start:
Key points

Section not matched: key
Full section start:
Key points

Section not matched: author
Full section start:
Author contributions

Section not matched: results
Full section start:
Results and discussion

Section not matched: conflict
Full section start:
Conflict of interest

Section not matched: results
Full section start:
Results

Section not matched: key
Full section start:
Key points

Section not matched: results
Full section start:
Results

Section not matched: supplementary
Full section start:
Supplementary Material

Section not matched: highlights
Full section start:
Highlights

Section not matched: commentary
Full section start:
COMMENTARY

Section not matched:
Full section start:
1

Section not matched: abbreviations
Full section start:
Abbreviations

Section not matched: abbreviations
Full section start:
Abbreviations

Section not matched: abbreviations
Full section start:
Abbreviations

Section not matched: results
Full section start:
Results

Section not matched: key
Full section start:
Key points

Section not matched: results
Full section start:
Results

Section not matched: instruction
Full section start:
Instruction

Section not matched: results
Full section start:
Results and Discussion

Section not matched: materials
Full section start:
Materials and Methods

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: highlights
Full section start:
Highlights

Section not matched: case
Full section start:
Case Presentation

Section not matched: abbreviations
Full section start:
Abbreviations

Section not matched: conflicts
Full section start:
Conflicts of interest

Section not matched: main
Full section start:
Main

Section not matched: abbreviations
Full section start:
Abbreviations

Section not matched: results
Full section start:
Results

Section not matched: highlights
Full section start:
Highlights

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: conflict
Full section start:
Conflict of interest

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: main
Full section start:
Main

Section not matched: production
Full section start:
Production of Type II Thioesterase GrsT

Section not matched: results
Full section start:
Results and Discussion

Section not matched: highlights
Full section start:
Highlights

Section not matched: results
Full section start:
Results

Section not matched: abbreviations
Full section start:
Abbreviations:

Section not matched: statement
Full section start:
Statement of Need

Section not matched: conflicts
Full section start:
Conflicts of interest

Section not matched: credit
Full section start:
Credit author statement

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: publishers
Full section start:
Publisher’s note

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: instruction
Full section start:
1 Instruction

Section not matched:
Full section start:
1

Section not matched: results
Full section start:
Results

Section not matched: data
Full section start:
Data Summary

Section not matched: methods
Full section start:
Methods

Section not matched: materials
Full section start:
Materials and Methods

Section not matched: methods
Full section start:
Methods

Section not matched: highlights
Full section start:
Highlights

Section not matched: main
Full section start:
Main

Section not matched: author
Full section start:
Author Contributions

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: announcement
Full section start:
ANNOUNCEMENT

Section not matched: highlights
Full section start:
Highlights

Section not matched: highlights
Full section start:
Highlights

Section not matched: observation
Full section start:
OBSERVATION

Section not matched: supplementary
Full section start:
Supplementary Material

Section not matched: results
Full section start:
Results

Section not matched: main
Full section start:
Main

Section not matched: mathematic
Full section start:
1. Mathematic Models in Fermentation Process Control

Section not matched: results
Full section start:
Results

Section not matched: abbreviations
Full section start:
Abbreviations

Section not matched: highlights
Full section start:
Highlights

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results and Discussion

Section not matched: fusions
Full section start:
Fusions at a conserved NAHVILEE motif result in stalled intermediates

Section not matched: main
Full section start:
Main

Section not matched: methods
Full section start:
Methods

Section not matched: main
Full section start:
Main

Section not matched: main
Full section start:
Main

Section not matched: main
Full section start:
Main

Section not matched: highlights
Full section start:
Highlights

Section not matched: main
Full section start:
Main

Section not matched: results
Full section start:
Results

Section not matched: takeaway
Full section start:
Take-away

Section not matched: methods
Full section start:
Methods and materials

Section not matched: announcement
Full section start:
ANNOUNCEMENT

Section not matched: main
Full section start:
Main

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results and Discussion

Section not matched: main
Full section start:
Main

Section not matched: results
Full section start:
Results and Discussion

Section not matched: abbreviations
Full section start:
Abbreviations

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: results
Full section start:
Results

Section not matched: declaration
Full section start:
Declaration of Competing Interest

Section not matched: announcement
Full section start:
ANNOUNCEMENT

Section not matched: materials
Full section start:
Materials and methods

Section not matched: different
Full section start:
Different cobamide-dependent enzymes in a single organism can have distinct cobamide preferences

Section not matched: data
Full section start:
Data availability

Section not matched: abbreviations
Full section start:
Abbreviations

Section not matched: abbreviations
Full section start:
Abbreviations

Section not matched: results
Full section start:
Results

Section not matched: full
Full section start:
Full Text Availability

Section not matched: main
Full section start:
Main

Section not matched: main
Full section start:
Main

Section not matched: methods
Full section start:
Methods

Section not matched: main
Full section start:
Main

Section not matched: results
Full section start:
Results

Section not matched: supporting
Full section start:
Supporting Information

Section not matched: announcement
Full section start:
ANNOUNCEMENT

Section not matched: abbreviations
Full section start:
Abbreviations:

In [17]:
# Create a filtered dictionary (excluding author sections)
filtered_text = {}
original_text = {}
for doc_id, sections in full_text.Text.items():
    filtered_sections = {}
    remove_sections = set()  # Track sections to exclude
    
    # First pass: Identify author sections to exclude
    for section_name, section_content in sections.items():
        mini_list = section_content[0:2]
        text_mini = ' '.join(mini_list).lower()
        if 'author' in text_mini and not text_mini.startswith(('materials', 'methods')):
            remove_sections.add(section_name)
        elif 'acknowledgements' in text_mini:
            remove_sections.add(section_name)
        elif 'funding' in text_mini:
            remove_sections.add(section_name)
        elif 'supplementary' in text_mini:
            remove_sections.add(section_name)
        elif 'supporting information' in text_mini and not 'see supporting information' in text_mini:
            remove_sections.add(section_name)
        elif 'ethics statement' in text_mini and not text_mini.startswith(('materials', 'methods')):
            remove_sections.add(section_name)
        elif 'ethic approval' in text_mini and not text_mini.startswith(('materials', 'methods')):
            remove_sections.add(section_name)
    # Second pass: Build filtered dictionary
    for section_name, section_content in sections.items():
        if section_name not in remove_sections:
            filtered_sections[section_name] = section_content
    original_text[doc_id] = sections
    filtered_text[doc_id] = filtered_sections

In [18]:
def total_size(obj, seen=None):
    if seen is None:
        seen = set()
    obj_id = id(obj)
    if obj_id in seen:
        return 0
    seen.add(obj_id)
    size = sys.getsizeof(obj)
    if isinstance(obj, (list, tuple, set, frozenset)):
        size += sum(total_size(i, seen) for i in obj)
    elif isinstance(obj, dict):
        size += sum(total_size(k, seen) + total_size(v, seen) for k, v in obj.items())
    return size

list_var = original_text
dict_var = filtered_text 

print(f"Total size of list: {total_size(list_var)} bytes")
print(f"Total size of dict: {total_size(dict_var)} bytes")

Total size of list: 583196456 bytes
Total size of dict: 575231805 bytes

In [19]:
import re

def replace_non_uppercase_newlines(text):
    """
    Replaces newlines with spaces when:
    - The newline is NOT preceded by an uppercase letter AND
    - The newline is NOT followed by an uppercase letter
    (i.e., only replaces when both sides are lowercase/non-letters)
    Preserves newlines near uppercase letters (sentence boundaries).
    """
    # Combined pattern using negative lookarounds
    return re.sub(
        r'(?<![A-Z])\n(?![A-Z])', 
        ' ', 
        text, 
        flags=re.MULTILINE
    )

# Example usage:
sample_text = """This is a test\nof the emergency\nBroadcast system.
Here's another\nexample with Mixed\nCase letters.
Numbers like 1\n2 should stay.
But lowercase\nconnections should merge.
UPPERCASE\nCONNECTION stays.\n"""
print(replace_non_uppercase_newlines(sample_text))

This is a test of the emergency
Broadcast system.
Here's another example with Mixed
Case letters.
Numbers like 1 2 should stay.
But lowercase connections should merge.
UPPERCASE
CONNECTION stays.

In [22]:
# 2. Create a NEW dictionary for processed content
processed_text = {}

for doc_id, sections in filtered_text.items():
    processed_sections = {}
    
    for section_name, section_content in sections.items():
        # Special processing for introduction sections
        if section_name == 'Section_0':
            processed_content = process_introduction_section(
                section_content,
                compiled_patterns,
                section_starters
            )
            if processed_content:  # Only keep if we got valid content
                processed_content = 'Introduction:\n'+processed_content
                processed_content = re.sub(r'\s{2,}', ' ', processed_content) 
                processed_sections[section_name] = replace_non_uppercase_newlines(processed_content)
                
        else:
            # For other sections, keep original or add your processing
            section_content = ' '.join(section_content)
            section_content = re.sub(r'\s{2,}', ' ', section_content)  # Replace 2+ spaces with 1

            section_content = replace_non_uppercase_newlines(section_content)
            processed_sections[section_name] = section_content  # Or custom processing
    
    if processed_sections:  # Only add if we have content
        processed_text[doc_id] = processed_sections

# Now use processed_text for your analysis
print(f"Processed {len(processed_text)} documents")

Processed 5911 documents

In [23]:
import re

def remove_dna_sequences(text):
    """
    Removes DNA sequences in the format 5′-XXXXXXX-3′ from text.
    """
    # Pattern explanation:
    # 5′       - literal 5′
    # -?       - optional hyphen
    # [ACGT]+  - one or more DNA nucleotides (A, C, G, T)
    # -?       - optional hyphen
    # 3′       - literal 3′
    return re.sub(r'5′[-]?[ACGTNacgnt]+[-]?3′', '', text)

# Example usage:
sample_text = "This contains a DNA sequence 5′-GAGACACAATTCATCGATGGTTAGTG-3′ to remove."
clean_text = remove_dna_sequences(sample_text)
print(clean_text)  # Output: "This contains a DNA sequence  to remove."

This contains a DNA sequence  to remove.

In [25]:
complete_data = {}
for idx, text in processed_text.items():
    new_line = replace_non_uppercase_newlines('\n'.join(text.values()))
    new_line = remove_dna_sequences(new_line)    
    complete_data[idx]=new_line

In [26]:
pubmed_text = pd.DataFrame([complete_data]).T
pubmed_text.columns  = ['Text']
pubmed_text.index.name='PM_ID'
pubmed_text.head()

                                                       Text
PM_ID
11934354  Introduction:\nThe present manuscript presents...
15588323  Introduction:\nA number of reviews [7-12] prov...
12620118  Introduction:\nThe transcription of this promo...
15341664  Introduction:\nWe report in this article on a ...
15904518  Introduction:\nCultures with these engineered ...

full_text = full_text.loc[~full_text.str.len()<1000]

full_text.loc[full_text.str.lower().str.contains('retraction to')]

In [ ]:
full_text.shape

In [ ]:
classified_data.head()

In [ ]:
classified_data.index

In [ ]:
pubmed_text.index

In [27]:

#Join data
classified_data = classified_data.set_index('PM_ID')
classified_data_with_text = pd.concat([classified_data,pubmed_text], axis=1)

In [28]:
classified_data_with_text

,Unnamed: 0.1,Unnamed: 0,Title,Abstract,Journal,Year,PMC_ID,DOI,Type,Author,Classification,Text
PM_ID,,,,,,,,,,,,
10618204,13,13,Increased production of zeaxanthin and other p...,The psbAII locus was used as an integration pl...,Applied and environmental microbiology,2000.0,91786.0,10.1128/AEM.66.1.64-72.2000,"Journal Article,Research Support, U.S. Gov't, ...","[ForeName:D,LastName:Lagarde] [ForeName:L,Last...",1,NaN
10618209,14,14,Expression of Alcaligenes eutrophus flavohemop...,Expression of the vhb gene encoding hemoglobin...,Applied and environmental microbiology,2000.0,91791.0,10.1128/AEM.66.1.98-104.2000,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:A D,LastName:Frey] [ForeName:J E,Las...",1,NaN
10631776,31,31,Environmental biotechnology.,There is an increasing interest in environment...,Trends in biotechnology,2000.0,NaN,10.1016/s0167-7799(99)01399-2,"Journal Article,","[ForeName:L P,LastName:Wackett]",1,NaN
10649237,50,50,Altered regulation of pyruvate kinase or co-ov...,Glycolytic fluxes in resting Escherichia coli ...,Biotechnology and bioengineering,2000.0,NaN,10.1002/(sici)1097-0290(20000305)67:5<623::aid...,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:M,LastName:Emmerling] [ForeName:J E,...",1,NaN
10649449,51,51,Cloning and characterization of the Yarrowia l...,The squalene synthase (SQS) gene encodes a key...,"Yeast (Chichester, England)",2000.0,NaN,10.1002/(SICI)1097-0061(200002)16:3<197::AID-Y...,"Journal Article,Research Support, Non-U.S. Gov...","[ForeName:S,LastName:Merkulov] [ForeName:F,Las...",1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
40572208,152913,152913,Heterologous Expression of the Nitrogen-Fixing...,Microbially mediated biological nitrogen fixat...,Microorganisms,2025.0,12195393.0,10.3390/microorganisms13061320,"Journal Article,","[ForeName:Xiuling,LastName:Wang] [ForeName:Shi...",1,Introduction:\nThis article reports the first ...
40573728,152927,152927,Functional Characterization of Squalene Epoxid...,The medicinal plant <i>Siraitia grosvenorii</i...,"Plants (Basel, Switzerland)",2025.0,NaN,10.3390/plants14121740,"Journal Article,","[ForeName:Huan,LastName:Zhao] [ForeName:Ze,Las...",1,NaN
40577193,152973,152973,Structural characterization and dynamics of Ad...,"<i>Clostridium thermocellum</i>, a cellulolyti...",eLife,2025.0,NaN,10.7554/eLife.96966,"Journal Article,","[ForeName:Samantha J,LastName:Ziegler] [ForeNa...",1,NaN
40578703,152993,152993,Overcoming glucose repression through cellobio...,Pectin-rich biomass is a promising substrate f...,Bioresource technology,2025.0,NaN,10.1016/j.biortech.2025.132892,"Journal Article,","[ForeName:Dahye,LastName:Lee] [ForeName:Deokye...",1,NaN
40579636,152997,152997,Genetically engineering central carbon and nit...,Poly-γ-glutamic acid (γ-PGA) is a biopolymer w...,World journal of microbiology & biotechnology,2025.0,NaN,10.1007/s11274-025-04467-8,"Journal Article,","[ForeName:Jishuai,LastName:Qi] [ForeName:Rui,L...",1,NaN

In [ ]:
classified_data_with_text.dropna(subset=['Text']).shape

In [ ]:
classified_data_with_text

### Revisar los casos con 36 caracteres :O

classified_data_with_text.dropna(subset=['Text']).Text.apply(len).sort_values().head(10)

classified_data_with_text.to_json('PMC_info_v2.json')

In [ ]:
classified_data_with_text = pd.read_json('PMC_info_v2.json')

classified_data_with_text.Text.dropna()

# Get the full text from Unpywall urls

## Get Unpywall url

In [29]:
classified_data_with_text[~classified_data_with_text['Text'].isna()].shape

(5911, 12)

In [30]:
classified_data_with_text.shape

(16271, 12)

In [31]:
missing = classified_data_with_text[classified_data_with_text['Text'].isna()].copy()

In [32]:
missing.shape

(10360, 12)

In [33]:
def get_unpywall_url(doi):
#for doi in missing.DOI:
    try:
        all_links = Unpywall.get_all_links(doi=doi)
        return(all_links)
    except:
        return(None)

In [34]:
missing.loc[:,'Full_links'] = missing.DOI.apply(get_unpywall_url)
missing.loc[:,'Full_links'] = missing.loc[:,'Full_links'].apply(lambda x: x if x else None)

In [36]:
missing.to_json('missing_v2.json')

missing = pd.read_json('missing.json')

In [37]:
missing.loc[:,'Full_links'] = missing.loc[:,'Full_links'].apply(lambda x: x if x else None)

In [38]:
missing = missing.dropna(subset=['Full_links'])

missing

In [39]:
print('AMAMAAIUU')

AMAMAAIUU

## Get PDFs

In [40]:
import subprocess

In [41]:
    
import logging

# Configure logging (you can set this up once at the start of your script)
logging.basicConfig(
    level=logging.INFO,
    format='%(message)s',
    handlers=[
        logging.FileHandler('doiprocess.log'),  # Log to file
        logging.StreamHandler()  # Also log to console
    ]
)

In [44]:
articles_dois = missing.DOI.to_list()
batches_len = 100

batched_art_dois = [articles_dois[i * batches_len:(i + 1) * batches_len] 
                   for i in range((len(articles_dois) + batches_len- 1) // batches_len )]

print(len(batched_art_dois))

32

In [ ]:
import os
import json
import time
import logging
import pandas as pd
import subprocess
import concurrent.futures
from io import BytesIO
from pdfminer.high_level import extract_text_to_fp
from pdfminer.layout import LAParams

# === Configuration ===
DOI_FILE = './temp_pdfs/dois.txt'
RESULTS_FILE = './temp_pdfs/result.csv'
PDF_DIR = './temp_pdfs'
BATCH_SAVE_INTERVAL = 5
BATCH_TIMEOUT = 1800  # seconds
PDF_TIMEOUT = 1200   # seconds (20 minutes)

# === Logging Setup ===
logging.basicConfig(
    level=logging.INFO,
    format='%(message)s',
)

# === State ===
full_texts = {}
failed_batches = []
failed_pdfs = []
batch_counter = 0
save_index = 0

# === Text Extraction Helper ===
def extract_text_safe(file_path):
    with open(file_path, 'rb') as data:
        output = BytesIO()
        laparams = LAParams(word_margin=0.2)
        extract_text_to_fp(data, output, laparams=laparams)
        return output.getvalue().decode()

# === Main Process ===
logging.info("Starting DOI processing pipeline...")

for i, batch in enumerate(batched_art_dois):
    batch_start = time.time()
    logging.info(f"Processing batch {i + 1} with {len(batch)} DOIs...")

    try:
        # Write DOIs to file
        with open(DOI_FILE, 'w') as f:
            for doi in batch:
                f.write(f"{doi}\n")
        logging.debug(f"Written {len(batch)} DOIs to {DOI_FILE}")

        # Wait 1 minute before PyPaperBot
        logging.info("Waiting 10 seconds before running PyPaperBot...")
        time.sleep(10)

        # Run PyPaperBot with timeout
        logging.info("Running PyPaperBot subprocess...")
        subprocess.run(
            f'python -m PyPaperBot --doi-file={DOI_FILE} --dwn-di="{PDF_DIR}" --restrict="1"',
            shell=True,
            timeout=BATCH_TIMEOUT
        )

        # Read result CSV
        try:
            results = pd.read_csv(RESULTS_FILE).dropna(subset=['PDF Name'])
            logging.info(f"Retrieved {len(results)} results with valid PDFs.")
        except Exception as e:
            logging.error(f"Failed to read {RESULTS_FILE}: {e}")
            failed_batches.append(batch)
            continue

        for found_doi, pdf in results.set_index('DOI')['PDF Name'].items():
            file_path = os.path.join(PDF_DIR, pdf)
            logging.info(f"Extracting text for DOI {found_doi} from {pdf}...")

            pdf_start = time.time()
            try:
                with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
                    future = executor.submit(extract_text_safe, file_path)
                    text = future.result(timeout=PDF_TIMEOUT)

                duration = time.time() - pdf_start
                logging.info(f"Text extraction for DOI {found_doi} completed in {duration:.2f} seconds")

                text = cut_unrelevant_info(text)
                full_texts[found_doi] = text

            except concurrent.futures.TimeoutError:
                logging.warning(f"Text extraction for DOI {found_doi} timed out after {PDF_TIMEOUT} seconds")
                failed_pdfs.append(found_doi)
            except Exception as e:
                logging.error(f"Failed to extract text for {file_path}: {e}")
                failed_pdfs.append(found_doi)

        # Clean up temporary PDFs
        logging.info("Cleaning up temporary PDF files...")
        subprocess.run(f'rm -f {PDF_DIR}/*.pdf', shell=True)

        batch_counter += 1

        # Save every N batches
        if batch_counter % BATCH_SAVE_INTERVAL == 0:
            out_file = f'full_texts_v2_part_{save_index}.json'
            with open(out_file, 'w') as f:
                json.dump(full_texts, f)
            logging.info(f"Saved batch data to {out_file}")
            full_texts = {}
            save_index += 1

        duration = time.time() - batch_start
        logging.info(f"Finished batch {i + 1} in {duration:.2f} seconds")

    except subprocess.TimeoutExpired:
        logging.error(f"Batch {i + 1} timed out after {BATCH_TIMEOUT} seconds")
        failed_batches.append(batch)
    except Exception as e:
        logging.error(f"Unexpected error during batch {i + 1}: {e}")
        failed_batches.append(batch)

# Save remaining full_texts
if full_texts:
    out_file = f'full_texts_part_{save_index}.json'
    with open(out_file, 'w') as f:
        json.dump(full_texts, f)
    logging.info(f"Saved remaining data to {out_file} (final)")

# Save failed batches
if failed_batches:
    with open('failed_batches.json', 'w') as f:
        json.dump(failed_batches, f)
    logging.warning(f"{len(failed_batches)} batches failed and were saved to failed_batches.json")

# Save failed PDFs
if failed_pdfs:
    with open('failed_pdfs.json', 'w') as f:
        json.dump(failed_pdfs, f)
    logging.warning(f"{len(failed_pdfs)} individual PDFs failed and were saved to failed_pdfs.json")

logging.info("DOI processing complete.")

In [ ]:


# -----------------------------------------------------------
# 2nd-pass: re-run the batches that failed the first time
# -----------------------------------------------------------
import json, os, time, subprocess, concurrent.futures, pandas as pd
from io import BytesIO
from pdfminer.high_level import extract_text_to_fp
from pdfminer.layout import LAParams

# ---- Load the failed batch list (skip if the file is missing) ----
if not os.path.exists('failed_batches.json'):
    print("Nothing to retry – 'failed_batches.json' not found.")
    exit()

with open('failed_batches.json', 'r') as fh:
    retry_batches = json.load(fh)

print(f"Retrying {len(retry_batches)} batches from failed_batches.json …")

# ---- Re-initialise state just for the retry pass ----
full_texts      = {}
failed_batches2 = []      # failures on the 2nd attempt
failed_pdfs2    = []
save_index      = 0
BATCH_SAVE_INTERVAL = 5   # or reuse the constant you had before
ATTEMPT_TAG     = "try_2" # suffix for all output filenames

def extract_text_safe(fp):
    with open(fp, 'rb') as data:
        out = BytesIO()
        extract_text_to_fp(data, out, laparams=LAParams(word_margin=0.2))
        return out.getvalue().decode()

for i, batch in enumerate(retry_batches, start=1):
    batch_start = time.time()
    print(f"[TRY-2] Batch {i}/{len(retry_batches)} – {len(batch)} DOIs")

    try:
        # ---- identical steps as first pass ----
        with open(DOI_FILE, 'w') as fh:
            fh.writelines([doi + "\n" for doi in batch])

        time.sleep(10)
        subprocess.run(
            f'python -m PyPaperBot --doi-file={DOI_FILE} --dwn-di="{PDF_DIR}" --restrict="1"',
            shell=True,
            timeout=BATCH_TIMEOUT
        )

        try:
            results = pd.read_csv(RESULTS_FILE).dropna(subset=['PDF Name'])
        except Exception as exc:
            print(f"  ✗ could not read {RESULTS_FILE}: {exc}")
            failed_batches2.append(batch)
            continue

        for doi, pdf in results.set_index('DOI')['PDF Name'].items():
            pdf_path = os.path.join(PDF_DIR, pdf)
            try:
                with concurrent.futures.ThreadPoolExecutor(max_workers=1) as ex:
                    fut = ex.submit(extract_text_safe, pdf_path)
                    text = fut.result(timeout=PDF_TIMEOUT)

                full_texts[doi] = cut_unrelevant_info(text)

            except concurrent.futures.TimeoutError:
                print(f"  ✗ timeout on {doi}")
                failed_pdfs2.append(doi)
            except Exception as exc:
                print(f"  ✗ error on {doi}: {exc}")
                failed_pdfs2.append(doi)

        subprocess.run(f'rm -f {PDF_DIR}/*.pdf', shell=True)

        # ---- periodic dump ----
        if i % BATCH_SAVE_INTERVAL == 0:
            out = f'full_texts_v2_part_{save_index}_{ATTEMPT_TAG}.json'
            with open(out, 'w') as fh:
                json.dump(full_texts, fh)
            print(f"  ✓ wrote {out} ({len(full_texts)} docs)")
            full_texts.clear()
            save_index += 1

    except subprocess.TimeoutExpired:
        print(f"  ✗ batch timed out")
        failed_batches2.append(batch)
    except Exception as exc:
        print(f"  ✗ unexpected error: {exc}")
        failed_batches2.append(batch)

# ---- flush any remainder ----
if full_texts:
    out = f'full_texts_v2_part_{save_index}_{ATTEMPT_TAG}.json'
    with open(out, 'w') as fh:
        json.dump(full_texts, fh)
    print(f"  ✓ wrote {out} ({len(full_texts)} docs)")

# ---- save the new failure logs ----
if failed_batches2:
    with open('failed_batches_try_2.json', 'w') as fh:
        json.dump(failed_batches2, fh)
    print(f"Saved {len(failed_batches2)} still-failing batches → failed_batches_try_2.json")

if failed_pdfs2:
    with open('failed_pdfs_try_2.json', 'w') as fh:
        json.dump(failed_pdfs2, fh)
    print(f"Saved {len(failed_pdfs2)} still-failing PDFs    → failed_pdfs_try_2.json")

print("Second-pass retry finished.")

In [ ]:
#!/usr/bin/env python3
# -----------------------------------------------------------
# 3rd-pass: split each still-failing batch into 4 sub-batches
#           and retry them individually
# -----------------------------------------------------------
import os, json, time, subprocess, concurrent.futures, pandas as pd
from pathlib import Path
from io import BytesIO
from pdfminer.high_level import extract_text_to_fp
from pdfminer.layout import LAParams

SUB_BATCH_FACTOR    = 4        # split each failing batch into 4
OUTPUT_ATTEMPT_TAG  = 'try_3'
BATCH_SAVE_INTERVAL = 5        # dump JSON after this many sub-batches

# ---------- helper -----------------------------------------------------------
def extract_text_safe(fp):
    with open(fp, 'rb') as data:
        buf = BytesIO()
        extract_text_to_fp(data, buf, laparams=LAParams(word_margin=0.2))
        return buf.getvalue().decode()

def chunk(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]

# ---------- load still-failing batches --------------------------------------
if not Path('failed_batches_try_2.json').exists():
    print("Nothing to retry – 'failed_batches_try_2.json' not found.")
    raise SystemExit

with open('failed_batches_try_2.json') as fh:
    parent_batches = json.load(fh)

print(f"[TRY-3] Loaded {len(parent_batches)} parent batches from failed_batches_try_2.json")

# ---------- retry state ------------------------------------------------------
full_texts      = {}
failed_batches3 = []   # list of *sub-batches* (list[DOI]) still failing
failed_pdfs3    = []   # list of individual DOI strings
sub_counter     = 0    # counts sub-batches overall
save_index      = 0

# ---------- main loop --------------------------------------------------------
for p_idx, parent in enumerate(parent_batches):
    # split parent batch into four roughly-equal sub-batches
    sub_size = max(1, len(parent) // SUB_BATCH_FACTOR)
    sub_batches = list(chunk(parent, sub_size))

    for s_idx, sub in enumerate(sub_batches):
        sub_counter += 1
        t0 = time.time()
        print(f"[TRY-3] Parent:{p_idx} Sub:{s_idx} ({len(sub)} DOIs)")

        try:
            # --- write DOIs -----------------------------------------------
            with open(DOI_FILE, 'w') as fh:
                fh.writelines([d + "\n" for d in sub])

            # --- small pause & run PyPaperBot -----------------------------
            time.sleep(10)  # shorter pause than v2
            subprocess.run(
                f'python -m PyPaperBot --doi-file="{DOI_FILE}" --dwn-di="{PDF_DIR}" --restrict="1"',
                shell=True,
                timeout=BATCH_TIMEOUT
            )

            # --- read results --------------------------------------------
            try:
                res = pd.read_csv(RESULTS_FILE).dropna(subset=['PDF Name'])
            except Exception as exc:
                print(f"  ✗ CSV error: {exc}")
                failed_batches3.append(sub)
                continue

            # --- per-PDF extraction --------------------------------------
            for doi, pdf in res.set_index('DOI')['PDF Name'].items():
                pdf_path = os.path.join(PDF_DIR, pdf)
                try:
                    with concurrent.futures.ThreadPoolExecutor(max_workers=1) as ex:
                        fut = ex.submit(extract_text_safe, pdf_path)
                        text = fut.result(timeout=PDF_TIMEOUT)
                    full_texts[doi] = cut_unrelevant_info(text)
                except concurrent.futures.TimeoutError:
                    print(f"  ✗ timeout on {doi}")
                    failed_pdfs3.append(doi)
                except Exception as exc:
                    print(f"  ✗ error on {doi}: {exc}")
                    failed_pdfs3.append(doi)

            # --- clean tmp PDFs ------------------------------------------
            subprocess.run(f'rm -f {PDF_DIR}/*.pdf', shell=True)

            # --- periodic save -------------------------------------------
            if sub_counter % BATCH_SAVE_INTERVAL == 0:
                fname = (f'full_texts_v3_parent{p_idx}_sub{s_idx}_'
                         f'part{save_index}_{OUTPUT_ATTEMPT_TAG}.json')
                with open(fname, 'w') as fh:
                    json.dump(full_texts, fh)
                print(f"  ✓ wrote {fname} ({len(full_texts)} docs)")
                full_texts.clear()
                save_index += 1

            print(f"  ✓ completed in {time.time() - t0:.1f}s")

        except subprocess.TimeoutExpired:
            print("  ✗ sub-batch timed out")
            failed_batches3.append(sub)
        except Exception as exc:
            print(f"  ✗ unexpected error: {exc}")
            failed_batches3.append(sub)

# ---------- flush remainder --------------------------------------------------
if full_texts:
    fname = f'full_texts_v3_parentX_subY_part{save_index}_{OUTPUT_ATTEMPT_TAG}.json'
    with open(fname, 'w') as fh:
        json.dump(full_texts, fh)
    print(f"  ✓ wrote final {fname} ({len(full_texts)} docs)")

# ---------- write new failure logs ------------------------------------------
if failed_batches3:
    with open('failed_batches_try_3.json', 'w') as fh:
        json.dump(failed_batches3, fh)
    print(f"Saved {len(failed_batches3)} sub-batches → failed_batches_try_3.json")

if failed_pdfs3:
    with open('failed_pdfs_try_3.json', 'w') as fh:
        json.dump(failed_pdfs3, fh)
    print(f"Saved {len(failed_pdfs3)} PDFs → failed_pdfs_try_3.json")

print("Third-pass retry finished.")

In [ ]:
len(full_texts)

In [ ]:
extraction_full_text_0 = pd.read_json('full_texts_part_0.json')
len(extraction_full_text_0)

In [ ]:
import json
with open('full_texts_part_0.json', 'r') as f:
    data = json.load(f)
print(type(data))  # Check what type of data you have
#print(data[:5] if isinstance(data, list) else data)  # Print a sample

In [ ]:
pd.DataFrame([data])

In [ ]:
pd.DataFrame([full_texts])

In [ ]:
 pd.DataFrame([full_texts]).to_json('full_text.json')

for n in batched_art_dois[32]:
    print(n in  pd.DataFrame([full_texts]).columns)

In [ ]:
extraction_full_text = pd.read_json('full_text_full.json')
extraction_full_text = extraction_full_text.T
extraction_full_text.columns = ['Unpywall_text']

# read

In [52]:
import os
import json
import pandas as pd
from glob import glob

# Find all relevant files
json_files = glob('full_texts_*.json')

all_dfs = []

for file in json_files:
    try:
        with open(file, 'r') as f:
            data = json.load(f)
        df = pd.DataFrame([data]).T  # Make each DOI a row
        df.columns = ['Unpywall_text']
        all_dfs.append(df)
        print(f"✓ Loaded {file} with {len(df)} entries.")
    except Exception as e:
        print(f"✗ Failed to read {file}: {e}")

# Concatenate all into one DataFrame
extraction_full_text = pd.concat(all_dfs)
print(f"\n✅ Final concatenated dataset has {len(extraction_full_text)} rows.")

# Optional: reset index to make DOI a column
# extraction_full_text = extraction_full_text.reset_index().rename(columns={'index': 'DOI'})

# Optional: save to a single output
# extraction_full_text.to_json('full_text_combined.json')

✓ Loaded full_texts_v2_part_4.json with 438 entries.
✓ Loaded full_texts_v3_parent2_sub1_part1_try_3.json with 0 entries.
✓ Loaded full_texts_v3_parent1_sub0_part0_try_3.json with 1 entries.
✓ Loaded full_texts_v2_part_2.json with 494 entries.
✓ Loaded full_texts_v2_part_3.json with 491 entries.
✓ Loaded full_texts_v2_part_0.json with 492 entries.
✓ Loaded full_texts_v2_part_1.json with 496 entries.
✓ Loaded full_texts_v3_parent4_sub3_part3_try_3.json with 0 entries.
✓ Loaded full_texts_v3_parent3_sub2_part2_try_3.json with 1 entries.

✅ Final concatenated dataset has 2413 rows.

In [57]:
extraction_full_text = extraction_full_text.reset_index()
extraction_full_text.columns = ['DOI','Text']

In [60]:
extraction_full_text.head()

,DOI,Text
0,10.1016/j.chembiol.2019.02.004,Article\n\nRefactoring the Cryptic Streptophen...
1,10.1021/acssynbio.8b00465,Subscriber access provided by UNIV OF TEXAS DA...
2,10.1021/acssynbio.8b00168,Article\n\nSubscriber access provided by UNIV ...
3,10.1016/j.ecoenv.2019.02.071,Ecotoxicology and Environmental Safety 175 (20...
4,10.1016/j.ymben.2019.03.003,Accepted Manuscript\n\nExceptional solvent tol...

In [54]:
classified_data_with_text = pd.read_json('PMC_info_v2.json')

In [61]:
classified_data_with_text.head()

,Unnamed: 0.1,Unnamed: 0,Title,Abstract,Journal,Year,PMC_ID,DOI,Type,Author,Classification,Text
10618204,13,13,Increased production of zeaxanthin and other p...,The psbAII locus was used as an integration pl...,Applied and environmental microbiology,2000,91786.0,10.1128/AEM.66.1.64-72.2000,"Journal Article,Research Support, U.S. Gov't, ...","[ForeName:D,LastName:Lagarde] [ForeName:L,Last...",1,None
10618209,14,14,Expression of Alcaligenes eutrophus flavohemop...,Expression of the vhb gene encoding hemoglobin...,Applied and environmental microbiology,2000,91791.0,10.1128/AEM.66.1.98-104.2000,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:A D,LastName:Frey] [ForeName:J E,Las...",1,None
10631776,31,31,Environmental biotechnology.,There is an increasing interest in environment...,Trends in biotechnology,2000,NaN,10.1016/s0167-7799(99)01399-2,"Journal Article,","[ForeName:L P,LastName:Wackett]",1,None
10649237,50,50,Altered regulation of pyruvate kinase or co-ov...,Glycolytic fluxes in resting Escherichia coli ...,Biotechnology and bioengineering,2000,NaN,10.1002/(sici)1097-0290(20000305)67:5<623::aid...,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:M,LastName:Emmerling] [ForeName:J E,...",1,None
10649449,51,51,Cloning and characterization of the Yarrowia l...,The squalene synthase (SQS) gene encodes a key...,"Yeast (Chichester, England)",2000,NaN,10.1002/(SICI)1097-0061(200002)16:3<197::AID-Y...,"Journal Article,Research Support, Non-U.S. Gov...","[ForeName:S,LastName:Merkulov] [ForeName:F,Las...",1,None

In [73]:
# ── main DataFrame (the one with Unnamed:… etc.) ───────────────────────────
df_main = classified_data_with_text.copy()        # rename for clarity

# ── second DataFrame that holds DOI ↔ full-text mapping ────────────────────
df_text = extraction_full_text.copy()[['DOI', 'Text']]

# Step 1 – build a Series keyed by DOI
text_map = df_text.set_index('DOI')['Text']

# Step 2 – update the Text column in df_main only where we have a match
# If df_main had missing/None, they’ll be overwritten; otherwise kept as-is.
df_main['Text'] = df_main.apply(
    lambda row: text_map.get(row['DOI'], row['Text']),
    axis=1
)

# ✔ df_main['Text'] now contains original text OR the new one if DOI matched

In [64]:
df_main.Text.dropna()

10662693    cm7204.qxd  03/03/2000  08:38  Page 77\n\nForm...
10708651    Protein Engineering vol.13 no.2 pp.121–128, 20...
10742205    APPLIED AND ENVIRONMENTAL MICROBIOLOGY,\n0099-...
10742260    APPLIED AND ENVIRONMENTAL MICROBIOLOGY,\n0099-...
10835112    Protein Engineering vol.13 no.5 pp.377–384, 20...
                                  ...
40558924    Introduction:\nThe goal of our study was to co...
40559434    Introduction:\nIn the present work, the biosyn...
40564374    Introduction:\nIn this article, we report the ...
40572067    Introduction:\nThis study aims to enhance the ...
40572208    Introduction:\nThis article reports the first ...
Name: Text, Length: 8324, dtype: object

In [66]:
df_main.head()

,Unnamed: 0.1,Unnamed: 0,Title,Abstract,Journal,Year,PMC_ID,DOI,Type,Author,Classification,Text
10618204,13,13,Increased production of zeaxanthin and other p...,The psbAII locus was used as an integration pl...,Applied and environmental microbiology,2000,91786.0,10.1128/AEM.66.1.64-72.2000,"Journal Article,Research Support, U.S. Gov't, ...","[ForeName:D,LastName:Lagarde] [ForeName:L,Last...",1,None
10618209,14,14,Expression of Alcaligenes eutrophus flavohemop...,Expression of the vhb gene encoding hemoglobin...,Applied and environmental microbiology,2000,91791.0,10.1128/AEM.66.1.98-104.2000,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:A D,LastName:Frey] [ForeName:J E,Las...",1,None
10631776,31,31,Environmental biotechnology.,There is an increasing interest in environment...,Trends in biotechnology,2000,NaN,10.1016/s0167-7799(99)01399-2,"Journal Article,","[ForeName:L P,LastName:Wackett]",1,None
10649237,50,50,Altered regulation of pyruvate kinase or co-ov...,Glycolytic fluxes in resting Escherichia coli ...,Biotechnology and bioengineering,2000,NaN,10.1002/(sici)1097-0290(20000305)67:5<623::aid...,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:M,LastName:Emmerling] [ForeName:J E,...",1,None
10649449,51,51,Cloning and characterization of the Yarrowia l...,The squalene synthase (SQS) gene encodes a key...,"Yeast (Chichester, England)",2000,NaN,10.1002/(SICI)1097-0061(200002)16:3<197::AID-Y...,"Journal Article,Research Support, Non-U.S. Gov...","[ForeName:S,LastName:Merkulov] [ForeName:F,Las...",1,None

In [74]:
df_main = df_main.iloc[:,2:] 
df_main = df_main.loc[:, ~df_main.columns.isin(['Classification'])]

In [75]:
df_main.columns

Index(['Title', 'Abstract', 'Journal', 'Year', 'PMC_ID', 'DOI', 'Type',
       'Author', 'Text'],
      dtype='object')

In [76]:
df_main.to_json('full_text_articles.json.gz', orient='index', compression='gzip')

In [ ]:
check_save_file(classified_data_with_text, 'full_text_raw_9_june.json', 'Articles')