# Import

In [1]:
# Load EC-mapping functions
from apply_ec_nb_03 import *

# File management utilities
import sys
sys.path.append('../../../')
sys.path.append('../../')

from file_management import get_files_dir, check_save_file

# Data tools
import pandas as pd

📦 Loading organism-specific EC reference data...
✅ Loaded 1280389 gene–EC mappings for Escherichia coli
✅ Loaded 16817 gene–EC mappings for Saccharomyces cerevisiae
✅ Loaded 7418 gene–EC mappings for Corynebacterium glutamicum
✅ Loaded 27246 gene–EC mappings for Bacillus subtilis
✅ Loaded 3075 gene–EC mappings for Yarrowia lipolytica
✅ Loaded 70444 gene–EC mappings for Pseudomonas putida
✅ Loaded 1539 gene–EC mappings for Komagataella pastoris
✅ Loaded 13746 gene–EC mappings for Cupriavidus necator
✅ Loaded 3835 gene–EC mappings for Synechococcus elongatus
✅ Loaded 33349 gene–EC mappings for Lactococcus lactis

# Files

## Input

In [2]:
# Get input/output directory structure from file_management
_, INPUT_DIR, OUTPUT_DIR = get_files_dir()

# Input: full text + extracted genes
INPUT_FILE = OUTPUT_DIR + "/Articles/full_text_w_genes_25_09_26_new_v.json"

# Load file
full_text_df = pd.read_json(INPUT_FILE)

full_text_df.head()

,Title,Abstract,Journal,Year,PMC_ID,DOI,Type,Author,Text,Abstract_min,Title_min,Full_text_min,Old_name,Organism_Source,Organism,Genes,Gene_Source
10618204,Increased production of zeaxanthin and other p...,The psbAII locus was used as an integration pl...,Applied and environmental microbiology,2000,91786.0,10.1128/AEM.66.1.64-72.2000,"Journal Article,Research Support, U.S. Gov't, ...","[ForeName:D,LastName:Lagarde] [ForeName:L,Last...",None,psbAII overexpress Synechocystis . PCC psbAII ...,pigments techniques Synechocystis . PCC .,None,[Synechocystis PCC],title,[Synechocystis PCC],"[[crtB, P37294, syn:slr1255;, 2.5.1.32;], [crt...",abstract
10618209,Expression of Alcaligenes eutrophus flavohemop...,Expression of the vhb gene encoding hemoglobin...,Applied and environmental microbiology,2000,91791.0,10.1128/AEM.66.1.98-104.2000,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:A D,LastName:Frey] [ForeName:J E,Las...",None,vhb Vitreoscilla . (VHb) organisms microaerobi...,Alcaligenes eutrophus flavohemoprotein Vitreos...,None,[Escherichia coli],title,[Escherichia coli],None,not_found
10631776,Environmental biotechnology.,There is an increasing interest in environment...,Trends in biotechnology,2000,NaN,10.1016/s0167-7799(99)01399-2,"Journal Article,","[ForeName:L P,LastName:Wackett]",None,"world' maintain soil, water. biology. Plants r...",Environmental biotechnology.,None,None,not_found,None,None,not_found
10649237,Altered regulation of pyruvate kinase or co-ov...,Glycolytic fluxes in resting Escherichia coli ...,Biotechnology and bioengineering,2000,NaN,10.1002/(sici)1097-0290(20000305)67:5<623::aid...,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:M,LastName:Emmerling] [ForeName:J E,...",None,Glycolytic resting kinases (Pyk) stearothermop...,Altered co- phosphofructokinase glycolytic res...,None,[Escherichia coli],title,[Escherichia coli],None,not_found
10649449,Cloning and characterization of the Yarrowia l...,The squalene synthase (SQS) gene encodes a key...,"Yeast (Chichester, England)",2000,NaN,10.1002/(SICI)1097-0061(200002)16:3<197::AID-Y...,"Journal Article,Research Support, Non-U.S. Gov...","[ForeName:S,LastName:Merkulov] [ForeName:F,Las...",None,"squalene (SQS) encodes , farnesyl-diphosphate ...",Cloning lipolytica squalene (SQS1) erg9 .,None,"[Yarrowia lipolytica, Saccharomyces cerevisiae]",title,"[Saccharomyces cerevisiae, Yarrowia lipolytica]","[[SQS1, A6ZRL6_P53866A6ZRL6_P53866, sce:YNL224...",title

In [3]:
modifications_df = pd.read_json('Cleaned_modifications.json')

## Output

In [4]:
output_file = 'Test_normalized_v4.json'

# Process Gene Lists


	1.	Remove papers without gene data  
	2.	Fix nested list structure  
	3.	Extract organism + gene + EC number combos

In [5]:
# Keep only rows with valid gene extraction
genes_df = full_text_df.dropna(subset=["Genes"])

genes_df.head()

,Title,Abstract,Journal,Year,PMC_ID,DOI,Type,Author,Text,Abstract_min,Title_min,Full_text_min,Old_name,Organism_Source,Organism,Genes,Gene_Source
10618204,Increased production of zeaxanthin and other p...,The psbAII locus was used as an integration pl...,Applied and environmental microbiology,2000,91786.0,10.1128/AEM.66.1.64-72.2000,"Journal Article,Research Support, U.S. Gov't, ...","[ForeName:D,LastName:Lagarde] [ForeName:L,Last...",None,psbAII overexpress Synechocystis . PCC psbAII ...,pigments techniques Synechocystis . PCC .,None,[Synechocystis PCC],title,[Synechocystis PCC],"[[crtB, P37294, syn:slr1255;, 2.5.1.32;], [crt...",abstract
10649449,Cloning and characterization of the Yarrowia l...,The squalene synthase (SQS) gene encodes a key...,"Yeast (Chichester, England)",2000,NaN,10.1002/(SICI)1097-0061(200002)16:3<197::AID-Y...,"Journal Article,Research Support, Non-U.S. Gov...","[ForeName:S,LastName:Merkulov] [ForeName:F,Las...",None,"squalene (SQS) encodes , farnesyl-diphosphate ...",Cloning lipolytica squalene (SQS1) erg9 .,None,"[Yarrowia lipolytica, Saccharomyces cerevisiae]",title,"[Saccharomyces cerevisiae, Yarrowia lipolytica]","[[SQS1, A6ZRL6_P53866A6ZRL6_P53866, sce:YNL224...",title
10653745,A novel genetically engineered pathway for syn...,A new pathway to synthesize poly(hydroxyalkano...,Applied and environmental microbiology,2000,91890.0,10.1128/AEM.66.2.739-743.2000,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:S J,LastName:Liu] [ForeName:A,LastNa...",None,synthesize poly(hydroxyalkanoic ) (PHA) butyra...,poly(hydroxyalkanoic ) .,None,[Escherichia coli],title,[Escherichia coli],"[[phaC, A0A3L0W3F5, 0, 0]]",abstract
10662693,Formation of functional heterologous complexes...,Recently developed tools for the genetic manip...,Chemistry & biology,2000,NaN,10.1016/s1074-5521(00)00073-9,"Journal Article,","[ForeName:L,LastName:Tang] [ForeName:H,LastNam...",cm7204.qxd 03/03/2000 08:38 Page 77\n\nForm...,Recently tools polyketide (PKSs) technologies ...,"Formation complexes picromycin, oleandomycin p...",cm7204.qxd // : Formation complexes picromycin...,"[Escherichia coli, Saccharopolyspora erythraea]",full_text,"[Saccharopolyspora erythraea, Escherichia coli]","[[eryAI, A4F7N8_O33937_Q5UNP6, sen:SACE_0721;,...",full_text
10742205,Properties of engineered poly-3-hydroxyalkanoa...,To prepare medium-chain-length poly-3-hydroxya...,Applied and environmental microbiology,2000,91986.0,10.1128/AEM.66.4.1311-1320.2000,"Journal Article,Research Support, Non-U.S. Gov't,","[ForeName:Q,LastName:Ren] [ForeName:N,LastName...","APPLIED AND ENVIRONMENTAL MICROBIOLOGY,\n0099-...",prepare medium-chain-length poly--hydroxyalkan...,Properties poly--hydroxyalkanoates .,"APPLIED ENVIRONMENTAL MICROBIOLOGY, -//$. Copy...",[Escherichia coli],title,[Escherichia coli],"[[der, A0A023KS59_A0A0E0XX99_A0A0H2Z1F8_A0A0H3...",full_text

In [6]:
def flatten_gene_list(nested_list):
    """
    Some files contain a level 3 nest like: [[[pairs]]]
    If so, flatten to a level 2 list: [[pairs]]
    """
    if len(nested_list[0][0][0]) != 1:
        return [inner for outer in nested_list for inner in outer]
    else:
        return nested_list

# Apply
genes_df["Genes"] = genes_df["Genes"].apply(flatten_gene_list)

/var/folders/v6/y2v6wwn93yj5vvhl558fx2zc0000gn/T/ipykernel_36972/3827492486.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genes_df["Genes"] = genes_df["Genes"].apply(flatten_gene_list)

In [7]:
# Explode into individual gene entries
expanded_genes = genes_df.explode("Genes").reset_index(drop=True)

# Keep only organism + gene pair
gene_table = expanded_genes.loc[:, ["Organism", "Genes"]]
gene_table.head()

,Organism,Genes
0,[Synechocystis PCC],"[crtB, P37294, syn:slr1255;, 2.5.1.32;]"
1,[Synechocystis PCC],"[crtO, Q55808, syn:slr0088;, 0]"
2,"[Saccharomyces cerevisiae, Yarrowia lipolytica]","[SQS1, A6ZRL6_P53866A6ZRL6_P53866, sce:YNL224C..."
3,"[Saccharomyces cerevisiae, Yarrowia lipolytica]","[SQS1, Q6C233_Q9Y753Q6C233_Q9Y753Q6C233_Q9Y753..."
4,[Escherichia coli],"[phaC, A0A3L0W3F5, 0, 0]"

In [8]:
# Keep rows where the EC field is non-empty and non-zero
genes_with_ec = gene_table.loc[
    ~gene_table.Genes.str[-1].isin([0, "", []])
]

genes_with_ec.head()

,Organism,Genes
0,[Synechocystis PCC],"[crtB, P37294, syn:slr1255;, 2.5.1.32;]"
3,"[Saccharomyces cerevisiae, Yarrowia lipolytica]","[SQS1, Q6C233_Q9Y753Q6C233_Q9Y753Q6C233_Q9Y753..."
5,"[Saccharopolyspora erythraea, Escherichia coli]","[eryAI, A4F7N8_O33937_Q5UNP6, sen:SACE_0721;, ..."
6,"[Saccharopolyspora erythraea, Escherichia coli]","[eryAII, A4F7P0_Q5UNP5, sen:SACE_0723;, 2.3.1...."
7,"[Saccharopolyspora erythraea, Escherichia coli]","[eryAIII, A4F7P1_Q5UNP4_Q9S1G4, sen:SACE_0724;..."

In [9]:
ec_table = genes_with_ec.copy()

# EC list
ec_table["EC_search"] = (
    ec_table.Genes.str[-1]
    .str.rstrip(";")
    .str.split(";")
    .apply(set)  # unique ECs
)

# Gene name
ec_table["Gene"] = ec_table.Genes.str[0]

ec_table = ec_table[["Organism", "Gene", "EC_search"]]
ec_table.columns = ["Organism", "Genes", "EC_search"]
ec_table.head()

                                          Organism    Genes   EC_search
0                              [Synechocystis PCC]     crtB  {2.5.1.32}
3  [Saccharomyces cerevisiae, Yarrowia lipolytica]     SQS1  {2.5.1.21}
5  [Saccharopolyspora erythraea, Escherichia coli]    eryAI  {2.3.1.94}
6  [Saccharopolyspora erythraea, Escherichia coli]   eryAII  {2.3.1.94}
7  [Saccharopolyspora erythraea, Escherichia coli]  eryAIII  {2.3.1.94}

# Process EC Table

In [10]:
processed_ec_df = process_ec_df(ec_table)

processed_ec_df.head()

   Genes                  Organism   EC_search
0    AAC    Pseudomonas aeruginosa  {2.3.1.82}
1  AAD10  Saccharomyces cerevisiae   {1.1.1.-}
2  AAD14  Saccharomyces cerevisiae   {1.1.1.-}
3  AAD15  Saccharomyces cerevisiae   {1.1.1.-}
4   AAD3  Saccharomyces cerevisiae   {1.1.1.-}

In [18]:
processed_ec_df.shape

(9270, 3)

In [11]:
# Expand EC lists into rows
ec_expanded = processed_ec_df.explode("EC_search").drop_duplicates()

# Normalize organism field
ec_expanded["Organism"] = ec_expanded["Organism"].str.capitalize()

# Final dedupe
ec_expanded = ec_expanded.drop_duplicates()

ec_expanded.head()

   Genes                  Organism EC_search
0    AAC    Pseudomonas aeruginosa  2.3.1.82
1  AAD10  Saccharomyces cerevisiae   1.1.1.-
2  AAD14  Saccharomyces cerevisiae   1.1.1.-
3  AAD15  Saccharomyces cerevisiae   1.1.1.-
4   AAD3  Saccharomyces cerevisiae   1.1.1.-

In [12]:
# Reset index so Title becomes a column
modifications_df_reset = modifications_df.reset_index().rename(columns={"index": "Title"})

# Merge full text with modifications
merged_df = full_text_df.merge(modifications_df_reset, on="Title", how="left")

merged_df = merged_df[
    ["Title", "Organism", "Genes", "Gene_Source", "Modifications"]
]

merged_df.head()

,Title,Organism,Genes,Gene_Source,Modifications
0,Increased production of zeaxanthin and other p...,[Synechocystis PCC],"[[crtB, P37294, syn:slr1255;, 2.5.1.32;], [crt...",abstract,"[ipi -> expression, crtP -> was introduced, cr..."
1,Expression of Alcaligenes eutrophus flavohemop...,[Escherichia coli],None,not_found,NaN
2,Environmental biotechnology.,None,None,not_found,NaN
3,Altered regulation of pyruvate kinase or co-ov...,[Escherichia coli],None,not_found,[pyk -> overexpression]
4,Cloning and characterization of the Yarrowia l...,"[Saccharomyces cerevisiae, Yarrowia lipolytica]","[[SQS1, A6ZRL6_P53866A6ZRL6_P53866, sce:YNL224...",title,NaN

# Map Gene Modifications to EC Modifications

In [ ]:
merged_df["EC_Modifications"] = merged_df.apply(
    lambda row: map_modifications_to_ec_fixed(
        row,
        ec_expanded,
        verbose=False,
        allow_cross_organism_fallback=False
    ),
    axis=1
)

merged_df.head()

In [14]:
merged_df["EC_Modifications_Normalized"] = merged_df["EC_Modifications"].apply(
    extract_and_normalize_dict
)

merged_df.head()

,Title,Organism,Genes,Gene_Source,Modifications,EC_Modifications,EC_Modifications_Normalized
0,Increased production of zeaxanthin and other p...,[Synechocystis PCC],"[[crtB, P37294, syn:slr1255;, 2.5.1.32;], [crt...",abstract,"[ipi -> expression, crtP -> was introduced, cr...","{'ipi': {'EC_numbers': [], 'Modifications': ['...","{'ipi': {'EC_numbers': [], 'Normalized_Modific..."
1,Expression of Alcaligenes eutrophus flavohemop...,[Escherichia coli],None,not_found,NaN,{},{}
2,Environmental biotechnology.,None,None,not_found,NaN,{},{}
3,Altered regulation of pyruvate kinase or co-ov...,[Escherichia coli],None,not_found,[pyk -> overexpression],"{'pyk': {'EC_numbers': ['2.7.1.40'], 'Modifica...","{'pyk': {'EC_numbers': ['2.7.1.40'], 'Normaliz..."
4,Cloning and characterization of the Yarrowia l...,"[Saccharomyces cerevisiae, Yarrowia lipolytica]","[[SQS1, A6ZRL6_P53866A6ZRL6_P53866, sce:YNL224...",title,NaN,{},{}

In [17]:
merged_df.iloc[0].Modifications

['ipi -> expression',
 'crtP -> was introduced',
 'crtP -> expression',
 'crtB -> was introduced',
 'crtR -> overexpression',
 'crtB -> overexpression',
 'ipi -> overexpression',
 'crtB -> expression',
 'ipi -> was introduced',
 'crtR -> was introduced',
 'crtP -> overexpression',
 'crtR -> expression']

In [15]:
merged_df.to_json(output_file)