# Import

In [4]:
from choose_BIGG_05 import *

In [5]:
import sys
sys.path.append('../../../')
sys.path.append('../../')

from file_management import get_files_dir,check_save_file
_, INPUT_DIR, OUTPUT_DIR = get_files_dir()

In [6]:
import pandas as pd

# Files

## Input

In [7]:
original_df = pd.read_json('Test_normalised_classifed.json')
df_bigg_info = pd.read_json('Gene_X_BIGG.json')

# Analysis

In [8]:
daniel_gene_EC = original_df.loc[:,['Title','Organism','EC_Modifications_Classified_min_relv']]

In [9]:
daniel_gene_EC = daniel_gene_EC.dropna(subset=['EC_Modifications_Classified_min_relv'])

In [10]:
daniel_gene_EC.columns

Index(['Title', 'Organism', 'EC_Modifications_Classified_min_relv'], dtype='object')

In [11]:
daniel_gene_EC.columns = ['Title', 'Organism', 'EC_gene']

In [12]:
daniel_gene_EC.to_csv('org_ec_gene.csv')

In [13]:
daniel_gene_EC.head()

,Title,Organism,EC_gene
3,Altered regulation of pyruvate kinase or co-ov...,[Escherichia coli],"{'pyk': {'EC_numbers': ['2.7.1.40'], 'Classifi..."
5,A novel genetically engineered pathway for syn...,[Escherichia coli],"{'buk': {'EC_numbers': ['2.7.2.7'], 'Classifie..."
10,Properties of engineered poly-3-hydroxyalkanoa...,[Escherichia coli],"{'phbB': {'EC_numbers': ['1.1.1.36'], 'Classif..."
15,Metabolic engineering of carotenoid accumulati...,[Escherichia coli],"{'dxs': {'EC_numbers': ['2.2.1.7'], 'Classifie..."
22,Metabolic characterization of Lactococcus lact...,[Lactococcus lactis],"{'ldh': {'EC_numbers': ['1.1.1.27'], 'Classifi..."

In [33]:
daniel_gene_EC.loc[4373].EC_gene

{'FAS1': {'EC_numbers': ['3.1.2.14',
   '4.2.1.59',
   '2.3.1.86',
   '1.3.1.9',
   '2.3.1.39',
   '2.3.1.38'],
  'Classified_Modifications': [{'mod': 'overexpress', 'class': 'Positive'},
   {'mod': 'downregulat', 'class': 'Negative'}]},
 'FAS2': {'EC_numbers': ['1.1.1.100', '2.3.1.41', '2.3.1.86'],
  'Classified_Modifications': [{'mod': 'downregulat', 'class': 'Negative'}]}}

In [14]:
final_df = process_best_matches(df_bigg_info, pick_best_rows)

In [15]:
final_df.head()

,Gene,Paper_ID,Chosen_Reaction_ID,Chosen_XREF,Alternative_XREFs,Specific_Match_Score,Match_Count,Presence,Corrected_Fraction_Matched,Reaction_Corrected_Fraction_Matched,Fraction_Matched,Reaction_Fraction_Matched,Selection_Case
0,AAE,8268,[MNXR190571],[ACS],"[FACOAL60i;HMR_0168, HMR_0165, FACOAL80;FACOAL...",1,1,1,1.0,0.500,0.5,0.500,CASE_A: PREFER_TOP_MODEL (max_score>0)
1,AAT1,13075,"[MNXR95698, MNXR192556, MNXR105000, MNXR192685...","[ALATA_L, ASPTA, TYRTA, LEUTAi, PHETA1]","[3SALATAi;3SALATAim;AATG;AATGm;ASPA2, AATC;LCY...",1,1,1,1.0,0.333,1.0,0.333,CASE_C: TIED_BY_MATCHCOUNT_KEEP_MODEL
2,AAT2,4115,"[MNXR95698, MNXR192556, MNXR105000, MNXR192685...","[ALATA_L, ASPTA, TYRTA, LEUTAi, PHETA1]","[3SALATAi;3SALATAim;AATG;AATGm;ASPA2, AATC;LCY...",1,1,1,1.0,0.333,1.0,0.333,CASE_C: TIED_BY_MATCHCOUNT_KEEP_MODEL
3,AAT2,7146,"[MNXR95698, MNXR192556, MNXR105000, MNXR192685...","[ALATA_L, ASPTA, TYRTA, LEUTAi, PHETA1]","[3SALATAi;3SALATAim;AATG;AATGm;ASPA2, AATC;LCY...",1,1,1,1.0,0.333,1.0,0.333,CASE_C: TIED_BY_MATCHCOUNT_KEEP_MODEL
4,AAT2,7717,"[MNXR95698, MNXR192556, MNXR105000, MNXR192685...","[ALATA_L, ASPTA, TYRTA, LEUTAi, PHETA1]","[3SALATAi;3SALATAim;AATG;AATGm;ASPA2, AATC;LCY...",1,1,1,1.0,0.333,1.0,0.333,CASE_C: TIED_BY_MATCHCOUNT_KEEP_MODEL

In [16]:
final_df = add_matching_ecs_to_final(final_df, df_bigg_info)

In [18]:
final_df

,Gene,Paper_ID,Chosen_Reaction_ID,Chosen_XREF,Alternative_XREFs,Specific_Match_Score,Match_Count,Presence,Corrected_Fraction_Matched,Reaction_Corrected_Fraction_Matched,Fraction_Matched,Reaction_Fraction_Matched,Selection_Case,Chosen_XREF_to_Matching_ECs
0,AAE,8268,[MNXR190571],[ACS],"[FACOAL60i;HMR_0168, HMR_0165, FACOAL80;FACOAL...",1,1,1,1.0,0.500,0.5,0.500,CASE_A: PREFER_TOP_MODEL (max_score>0),{'ACS': ['6.2.1.1']}
1,AAT1,13075,"[MNXR95698, MNXR192556, MNXR105000, MNXR192685...","[ALATA_L, ASPTA, TYRTA, LEUTAi, PHETA1]","[3SALATAi;3SALATAim;AATG;AATGm;ASPA2, AATC;LCY...",1,1,1,1.0,0.333,1.0,0.333,CASE_C: TIED_BY_MATCHCOUNT_KEEP_MODEL,"{'ALATA_L': ['2.6.1.1'], 'ASPTA': ['2.6.1.1'],..."
2,AAT2,4115,"[MNXR95698, MNXR192556, MNXR105000, MNXR192685...","[ALATA_L, ASPTA, TYRTA, LEUTAi, PHETA1]","[3SALATAi;3SALATAim;AATG;AATGm;ASPA2, AATC;LCY...",1,1,1,1.0,0.333,1.0,0.333,CASE_C: TIED_BY_MATCHCOUNT_KEEP_MODEL,"{'ALATA_L': ['2.6.1.1'], 'ASPTA': ['2.6.1.1'],..."
3,AAT2,7146,"[MNXR95698, MNXR192556, MNXR105000, MNXR192685...","[ALATA_L, ASPTA, TYRTA, LEUTAi, PHETA1]","[3SALATAi;3SALATAim;AATG;AATGm;ASPA2, AATC;LCY...",1,1,1,1.0,0.333,1.0,0.333,CASE_C: TIED_BY_MATCHCOUNT_KEEP_MODEL,"{'ALATA_L': ['2.6.1.1'], 'ASPTA': ['2.6.1.1'],..."
4,AAT2,7717,"[MNXR95698, MNXR192556, MNXR105000, MNXR192685...","[ALATA_L, ASPTA, TYRTA, LEUTAi, PHETA1]","[3SALATAi;3SALATAim;AATG;AATGm;ASPA2, AATC;LCY...",1,1,1,1.0,0.333,1.0,0.333,CASE_C: TIED_BY_MATCHCOUNT_KEEP_MODEL,"{'ALATA_L': ['2.6.1.1'], 'ASPTA': ['2.6.1.1'],..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10749,zwf1,14703,[MNXR192434],[G6PDH2r],"[G3PD2, G6PADH;G6PADHh, G6PBDH;G6PBDHh;G6PDHg,...",1,1,2,1.0,0.333,1.0,0.333,CASE_A: PREFER_TOP_MODEL (max_score>0),{'G6PDH2r': ['1.1.1.49']}
10750,zwf1,15355,[MNXR192434],[G6PDH2r],"[G3PD2, G6PADH;G6PADHh, G6PBDH;G6PBDHh;G6PDHg,...",1,1,2,1.0,0.333,1.0,0.333,CASE_A: PREFER_TOP_MODEL (max_score>0),{'G6PDH2r': ['1.1.1.49']}
10751,zwf1,15789,[MNXR192434],[G6PDH2r],"[G3PD2, G6PADH;G6PADHh, G6PBDH;G6PBDHh;G6PDHg,...",1,1,2,1.0,0.333,1.0,0.333,CASE_A: PREFER_TOP_MODEL (max_score>0),{'G6PDH2r': ['1.1.1.49']}
10752,zwf2,1120,[MNXR192434],[G6PDH2r],"[G3PD2, G6PADH;G6PADHh, G6PBDH;G6PBDHh;G6PDHg,...",1,1,2,1.0,0.333,1.0,0.333,CASE_A: PREFER_TOP_MODEL (max_score>0),{'G6PDH2r': ['1.1.1.49']}
10753,zwf2,3017,[MNXR192434],[G6PDH2r],"[G3PD2, G6PADH;G6PADHh, G6PBDH;G6PBDHh;G6PDHg,...",1,1,2,1.0,0.333,1.0,0.333,CASE_A: PREFER_TOP_MODEL (max_score>0),{'G6PDH2r': ['1.1.1.49']}

In [20]:
summary = pd.read_json('Gene_modification_Clasification.json')

In [21]:
summary.head()

   Paper_ID  Gene             EC_number Classification
0         3   pyk            [2.7.1.40]       Positive
1         5   buk             [2.7.2.7]       Positive
2         5   ptb            [2.3.1.19]       Positive
3         5  phaE  [6.2.1.30, 4.2.1.17]       Positive
4        10  phbB            [1.1.1.36]       Positive

In [22]:
final_df.head()

,Gene,Paper_ID,Chosen_Reaction_ID,Chosen_XREF,Alternative_XREFs,Specific_Match_Score,Match_Count,Presence,Corrected_Fraction_Matched,Reaction_Corrected_Fraction_Matched,Fraction_Matched,Reaction_Fraction_Matched,Selection_Case,Chosen_XREF_to_Matching_ECs
0,AAE,8268,[MNXR190571],[ACS],"[FACOAL60i;HMR_0168, HMR_0165, FACOAL80;FACOAL...",1,1,1,1.0,0.500,0.5,0.500,CASE_A: PREFER_TOP_MODEL (max_score>0),{'ACS': ['6.2.1.1']}
1,AAT1,13075,"[MNXR95698, MNXR192556, MNXR105000, MNXR192685...","[ALATA_L, ASPTA, TYRTA, LEUTAi, PHETA1]","[3SALATAi;3SALATAim;AATG;AATGm;ASPA2, AATC;LCY...",1,1,1,1.0,0.333,1.0,0.333,CASE_C: TIED_BY_MATCHCOUNT_KEEP_MODEL,"{'ALATA_L': ['2.6.1.1'], 'ASPTA': ['2.6.1.1'],..."
2,AAT2,4115,"[MNXR95698, MNXR192556, MNXR105000, MNXR192685...","[ALATA_L, ASPTA, TYRTA, LEUTAi, PHETA1]","[3SALATAi;3SALATAim;AATG;AATGm;ASPA2, AATC;LCY...",1,1,1,1.0,0.333,1.0,0.333,CASE_C: TIED_BY_MATCHCOUNT_KEEP_MODEL,"{'ALATA_L': ['2.6.1.1'], 'ASPTA': ['2.6.1.1'],..."
3,AAT2,7146,"[MNXR95698, MNXR192556, MNXR105000, MNXR192685...","[ALATA_L, ASPTA, TYRTA, LEUTAi, PHETA1]","[3SALATAi;3SALATAim;AATG;AATGm;ASPA2, AATC;LCY...",1,1,1,1.0,0.333,1.0,0.333,CASE_C: TIED_BY_MATCHCOUNT_KEEP_MODEL,"{'ALATA_L': ['2.6.1.1'], 'ASPTA': ['2.6.1.1'],..."
4,AAT2,7717,"[MNXR95698, MNXR192556, MNXR105000, MNXR192685...","[ALATA_L, ASPTA, TYRTA, LEUTAi, PHETA1]","[3SALATAi;3SALATAim;AATG;AATGm;ASPA2, AATC;LCY...",1,1,1,1.0,0.333,1.0,0.333,CASE_C: TIED_BY_MATCHCOUNT_KEEP_MODEL,"{'ALATA_L': ['2.6.1.1'], 'ASPTA': ['2.6.1.1'],..."

In [23]:
dataset_final = final_df.merge(summary[['Paper_ID','Gene','Classification']],
                                  on=['Paper_ID', 'Gene'],
    how='left'  # keep all rows from final_df
)

In [24]:
dataset_final.head()

,Gene,Paper_ID,Chosen_Reaction_ID,Chosen_XREF,Alternative_XREFs,Specific_Match_Score,Match_Count,Presence,Corrected_Fraction_Matched,Reaction_Corrected_Fraction_Matched,Fraction_Matched,Reaction_Fraction_Matched,Selection_Case,Chosen_XREF_to_Matching_ECs,Classification
0,AAE,8268,[MNXR190571],[ACS],"[FACOAL60i;HMR_0168, HMR_0165, FACOAL80;FACOAL...",1,1,1,1.0,0.500,0.5,0.500,CASE_A: PREFER_TOP_MODEL (max_score>0),{'ACS': ['6.2.1.1']},Positive
1,AAT1,13075,"[MNXR95698, MNXR192556, MNXR105000, MNXR192685...","[ALATA_L, ASPTA, TYRTA, LEUTAi, PHETA1]","[3SALATAi;3SALATAim;AATG;AATGm;ASPA2, AATC;LCY...",1,1,1,1.0,0.333,1.0,0.333,CASE_C: TIED_BY_MATCHCOUNT_KEEP_MODEL,"{'ALATA_L': ['2.6.1.1'], 'ASPTA': ['2.6.1.1'],...",Negative
2,AAT2,4115,"[MNXR95698, MNXR192556, MNXR105000, MNXR192685...","[ALATA_L, ASPTA, TYRTA, LEUTAi, PHETA1]","[3SALATAi;3SALATAim;AATG;AATGm;ASPA2, AATC;LCY...",1,1,1,1.0,0.333,1.0,0.333,CASE_C: TIED_BY_MATCHCOUNT_KEEP_MODEL,"{'ALATA_L': ['2.6.1.1'], 'ASPTA': ['2.6.1.1'],...",Positive
3,AAT2,7146,"[MNXR95698, MNXR192556, MNXR105000, MNXR192685...","[ALATA_L, ASPTA, TYRTA, LEUTAi, PHETA1]","[3SALATAi;3SALATAim;AATG;AATGm;ASPA2, AATC;LCY...",1,1,1,1.0,0.333,1.0,0.333,CASE_C: TIED_BY_MATCHCOUNT_KEEP_MODEL,"{'ALATA_L': ['2.6.1.1'], 'ASPTA': ['2.6.1.1'],...",Negative
4,AAT2,7717,"[MNXR95698, MNXR192556, MNXR105000, MNXR192685...","[ALATA_L, ASPTA, TYRTA, LEUTAi, PHETA1]","[3SALATAi;3SALATAim;AATG;AATGm;ASPA2, AATC;LCY...",1,1,1,1.0,0.333,1.0,0.333,CASE_C: TIED_BY_MATCHCOUNT_KEEP_MODEL,"{'ALATA_L': ['2.6.1.1'], 'ASPTA': ['2.6.1.1'],...",Negative

In [25]:
dataset_final.to_json('mapped_to_BIGG.json')